import {createHash} from 'node:crypto';import {getSource,SourceError} from './adapters';import {xmlText} from './feeds';import {feedMedia,publicUrl} from './media';import type {PublicMedia} from './media';import type {Loader,Loaded} from './types';
const articleHosts=new Set(['www.anofm.ro','anofm.ro','www.mai.gov.ro','mai.gov.ro','cnas.ro','www.cnas.ro','www.edu.ro','edu.ro','www.just.ro','just.ro','energie.gov.ro','www.energie.gov.ro','tpbi.ro','www.tpbi.ro','www.afir.ro','afir.ro','politiaromana.ro','www.politiaromana.ro']);
export function articleUrl(value:string){const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password||url.port&&url.port!=='443'||!articleHosts.has(url.hostname)||/^\/(?:wp-admin|wp-login|administrator|api)(?:\/|\.|$)/i.test(url.pathname))throw new SourceError('Această publicație nu are încă un cititor conectat.');const post=url.searchParams.get('p');url.search=post&&/^\d+$/.test(post)?'?p='+post:'';url.hash='';return url.href}
function htmlBlock(html:string,match:RegExp){const begin=match.exec(html);if(!begin)return '';const tag=begin[1],bodyStart=begin.index+begin[0].length,ends=new RegExp('<(\\/?)'+tag+'\\b[^>]*>','gi');ends.lastIndex=bodyStart;let depth=1;for(let m;(m=ends.exec(html));){depth+=m[1]?-1:1;if(depth===0)return html.slice(bodyStart,m.index)}throw new SourceError('Publicația nu a fost transmisă integral.')}
export function parseArticle(html:string,url:string):Loaded{if(!/<html\b|<!doctype html/i.test(html))throw new SourceError('Publicația nu a furnizat o pagină validă.');let body=htmlBlock(html,/<(div|section)\b[^>]*class=["'][^"']*\b(?:entry-content|article-content|article-body|post-content|td-post-content|jeg_post_content|news-details|field(?:--|-)name-body)\b[^"']*["'][^>]*>/i);if(!body){for(const m of html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const data=JSON.parse(m[1]),rows=Array.isArray(data)?data:data['@graph']||[data];const article=rows.find((r:any)=>r.articleBody&&/Article/i.test(String(r['@type'])));if(article){body=String(article.articleBody);break}}catch{}}}if(!body)throw new SourceError('Structura textului integral al acestei publicații trebuie adaptată. Textul fluxului rămâne disponibil.');const content=xmlText(body);if(!content.trim())throw new SourceError('Textul publicației este gol.');const published=html.match(/<meta\b[^>]*property=["']article:published_time["'][^>]*content=["']([^"']+)["']/i)?.[1]||null;return{publishedAt:published&&Number.isFinite(Date.parse(published))?new Date(published).toISOString():null,data:{content,textComplete:true,media:feedMedia(body,url),url}}}
export function parseArticlePage(html:string,url:string):Loaded{const parsed=parseArticle(html,url);parsed.data.title=xmlText(html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||'')||undefined;parsed.data.attachments=articleAttachments(html,url);return parsed}
export function parseWordPress(raw:string,url:string):Loaded{const decoded=JSON.parse(raw),rows=Array.isArray(decoded)?decoded:[decoded],item=rows.find((r:any)=>{try{const a=new URL(articleUrl(r.link)),b=new URL(url);return a.hostname.replace(/^www\./,'')===b.hostname.replace(/^www\./,'')&&(b.searchParams.has('p')?String(r.id)===b.searchParams.get('p'):a.pathname.replace(/\/$/,'')===b.pathname.replace(/\/$/,''))}catch{return false}});if(!item?.content?.rendered||item.content.protected)throw new SourceError('Publicația nu a oferit textul integral prin serviciul alternativ.');const content=xmlText(item.content.rendered);if(!content)throw new SourceError('Textul publicației este gol.');return {publishedAt:item.date_gmt?item.date_gmt+'Z':null,data:{title:xmlText(item.title?.rendered||''),content,textComplete:true,media:feedMedia(item.content.rendered,url),url,attachments:articleAttachments(item.content.rendered,url)}}}
export function articleAttachments(html:string,url:string){return [...html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].flatMap(m=>{const link=publicUrl(m[1],url);if(!link)return[];const u=new URL(link);return articleHosts.has(u.hostname)&&/\.(?:pdf|docx?|xlsx?|csv|zip)$/i.test(u.pathname)?[{url:link,title:xmlText(m[2])||u.pathname.split('/').at(-1),id:createHash('sha256').update(link).digest('hex')}]:[]})}
export const articleLoader=(value:string):Loader=>{const url=articleUrl(value);return{key:'article:'+createHash('sha256').update(url).digest('hex'),name:'Text integral · publicația instituției',url,version:'official.article-body.v4',ttl:3600,load:async()=>{
 // Serviciul WordPress se citește ÎNTÂI: date_gmt e momentul UTC publicat de
 // sursă, pe când meta description:published_time cărată de pagină aplică
 // aceeași oră GMT cu fusul local adăugat (probă TPBI 2026-10-08: 15:08Z real
 // vs 15:08+03:00 în meta) — feed-ul și fișa articolului trebuie să spună
 // același moment. Pagina HTML rămâne rezerva pentru gazdele fără wp-json.
 const u=new URL(url),post=u.searchParams.get('p'),slug=decodeURIComponent(u.pathname.split('/').filter(Boolean).at(-1)||'');
 if(post||slug){const endpoint=u.origin+'/wp-json/wp/v2/posts'+(post?'/'+post:'?'+new URLSearchParams({slug,_fields:'id,link,title,content,date_gmt'}));try{return parseWordPress(await getSource(endpoint,undefined,{maxBytes:8_000_000,timeoutMs:6000}),url)}catch(e){if(e instanceof SourceError&&e.retryAfter>0)throw e}}
 let originalError:unknown;try{return parseArticlePage(await getSource(url,undefined,{maxBytes:8_000_000,timeoutMs:6000}),url)}catch(e){originalError=e;if(e instanceof SourceError&&e.retryAfter>0)throw e}
 throw originalError}}};
const plain=(s:string)=>xmlText(s);
async function commonsMedia(files:string[],sourceUrl:string):Promise<PublicMedia[]>{if(!files.length)return [];const url='https://commons.wikimedia.org/w/api.php?'+new URLSearchParams({action:'query',format:'json',titles:files.map(f=>'File:'+f).join('|'),prop:'imageinfo',iiprop:'url|mime|extmetadata',iiurlwidth:'1400'});const d=JSON.parse(await getSource(url));const media:PublicMedia[]=[];for(const page of Object.values(d.query?.pages||{}) as any[]){const info=page.imageinfo?.[0];if(!info)continue;const actual=publicUrl(info.mime?.startsWith('video/')?info.url:info.thumburl||info.url);if(!actual)continue;const meta=info.extmetadata||{};media.push({kind:info.mime?.startsWith('video/')?'video':'image',url:actual,caption:String(page.title||'').replace(/^File:/,''),sourceUrl:publicUrl(info.descriptionurl)||sourceUrl,credit:plain(meta.Artist?.value||meta.Credit?.value||''),license:plain(meta.LicenseShortName?.value||'Licență neprecizată'),...(publicUrl(meta.LicenseUrl?.value)?{licenseUrl:publicUrl(meta.LicenseUrl.value)!}:{})})}return media}
export function parseFilmEntity(raw:string,id:string,labels:Record<string,string>={}):Loaded{const d=JSON.parse(raw),entity=d.entities?.[id];if(!entity||entity.id!==id||!entity.claims||entity.missing)throw new SourceError('Fișa completă a filmului nu este disponibilă.');const text=(s:any)=>s?.ro?.value||s?.en?.value||null;const human=(snak:any)=>{const value=snak.datavalue?.value;if(snak.snaktype==='novalue')return 'Nicio valoare declarată';if(snak.snaktype==='somevalue')return 'Valoare necunoscută';if(value===null||value===undefined)return 'Nefurnizat';if(typeof value!=='object')return String(value);if(value.id)return labels[value.id]||value.id;if(value.text)return value.text+(value.language?' ['+value.language+']':'');if(value.time)return value.time;if(value.amount)return value.amount+' '+(value.unit==='1'?'':labels[value.unit?.split('/').at(-1)]||value.unit);return JSON.stringify(value)};const details=Object.fromEntries(Object.entries(entity.claims).map(([property,statements]:[string,any])=>[labels[property]||property,statements.map((s:any)=>({value:human(s.mainsnak),rank:s.rank,qualifiers:Object.fromEntries(Object.entries(s.qualifiers||{}).map(([p,values]:[string,any])=>[labels[p]||p,values.map(human)])),references:s.references||[]}))]));const values=(p:string)=>(entity.claims[p]||[]).map((s:any)=>human(s.mainsnak));return{publishedAt:null,data:{id,title:text(entity.labels)||id,description:text(entity.descriptions),directors:values('P57'),cast:values('P161'),genres:values('P136'),runtime:values('P2047'),languages:values('P364'),countries:values('P495'),screenwriters:values('P58'),producers:values('P162'),production:values('P272'),cinematographers:values('P344'),composers:values('P86'),releaseDates:values('P577'),details,metadata:entity,url:'https://www.wikidata.org/wiki/'+id,textComplete:true,modifiedAt:entity.modified||null,media:[]}}}
export const filmDetailLoader=(id:string):Loader=>({key:'film-detail:'+id,name:'Wikidata · fișa publică integrală',url:'https://www.wikidata.org/wiki/'+id,version:'wikidata.film-complete.v1',ttl:86400,load:async()=>{const raw=await getSource('https://www.wikidata.org/wiki/Special:EntityData/'+id+'.json'),entity=JSON.parse(raw).entities?.[id];if(!entity?.claims)throw new SourceError('Fișa filmului nu poate fi citită.');const ids=new Set<string>(Object.keys(entity.claims));for(const statements of Object.values(entity.claims) as any[][])for(const s of statements){const v=s.mainsnak?.datavalue?.value;if(v?.id)ids.add(v.id);if(v?.unit?.match(/Q\d+$/))ids.add(v.unit.split('/').at(-1))}const all=[...ids],labels:Record<string,string>={};for(let at=0;at<all.length;at+=50){const response=JSON.parse(await getSource('https://www.wikidata.org/w/api.php?'+new URLSearchParams({action:'wbgetentities',ids:all.slice(at,at+50).join('|'),props:'labels',languages:'ro|en',format:'json'})));for(const item of Object.values(response.entities||{}) as any[])labels[item.id]=item.labels?.ro?.value||item.labels?.en?.value||item.id}const loaded=parseFilmEntity(raw,id,labels),files=['P18','P10'].flatMap(p=>(entity.claims[p]||[]).map((s:any)=>s.mainsnak?.datavalue?.value).filter((v:any)=>typeof v==='string'));try{loaded.data.media=await commonsMedia(files,loaded.data.url)}catch{loaded.data.mediaNote='Metadatele sunt complete; materialele Commons nu pot fi verificate în acest moment.'}return loaded}});
