import {type GeographicContext} from '../geographic-scope';
import {datastoreGeographicFilters} from '../tabular-geography';
import {getSource,SourceError} from './adapters';import type {Loader,Loaded} from './types';
import {read,utils} from 'xlsx';
import {downloadResource} from './resources';
export const directories:Record<string,{name:string;dataset:string;resource:string;period:string;note:string}>={schools:{name:'Rețeaua școlară',dataset:'69392a50-5750-4a54-90c1-d461de44da6d',resource:'280d52b6-4c5e-489d-9b48-3dd8961f56e0',period:'2025–2026',note:'Ediția 2025–2026 publicată în catalog. Verifică oferta curentă și contactele la școală.'},health:{name:'Clinici în registrul CNAS',dataset:'lista-furnizori',resource:'CLINIC',period:'31.03.2026',note:'Contracte CNAS la data publicării. Nu confirmă programări, locuri disponibile sau valabilitatea contractului astăzi.'},pharmacies:{name:'Farmacii în registrul CNAS',dataset:'lista-furnizori',resource:'FARM',period:'31.03.2026',note:'Furnizori contractați, nu puncte de lucru. Programul și stocurile nu sunt incluse.'},hospitals:{name:'Spitale în registrul CNAS',dataset:'lista-furnizori',resource:'SPITAL',period:'31.03.2026',note:'Contracte la data publicării. Nu reprezintă disponibilitatea paturilor sau programărilor.'}};
export function parseHealth(bytes:ArrayBuffer,kind:string,period:string):Loaded {const workbook=read(bytes,{type:'array'});const records=workbook.SheetNames.flatMap(name=>utils.sheet_to_json<Record<string,unknown>>(workbook.Sheets[name],{defval:null}).map(r=>({...r,_foaie:name})));if(!records.length||!Object.hasOwn(records[0],'Nume furnizor'))throw new SourceError('Structura registrului CNAS s-a schimbat.');const c=directories[kind];return{publishedAt:period,data:{title:c.name,period,note:c.note,fields:[...new Set(records.flatMap(r=>Object.keys(r)))],total:records.length,records}}}
export const directoryLoader=(kind:string,q='',page=0,context?:GeographicContext):Loader=>{const c=directories[kind];return{key:'directory:'+kind+(kind==='schools'?':'+(context?.active?JSON.stringify({q,locality:context.locality,county:context.county}):q)+':'+page:''),name:c.name,url:'https://data.gov.ro/dataset/'+c.dataset,version:'directory.complete-fields.v6',ttl:86400,load:async()=>{
 if(kind==='schools'){const params=new URLSearchParams({resource_id:c.resource,limit:'20',offset:String(page*20),...(q?{q}: {}),...(context?.active?{filters:JSON.stringify(datastoreGeographicFilters(['Localitate unitate','Judet PJ'],context))}:{})});const d=JSON.parse(await getSource('https://data.gov.ro/api/3/action/datastore_search?'+params));if(d.success!==true||!Array.isArray(d.result?.records)||!Array.isArray(d.result?.fields))throw new SourceError('Registrul școlar nu poate fi citit acum.');const fields=d.result.fields.map((f:any)=>String(f.id));return{publishedAt:c.period,data:{title:c.name,period:c.period,note:c.note,fields,total:d.result.total,paginated:true,page,pageSize:20,pages:Math.max(1,Math.ceil(d.result.total/20)),records:d.result.records}}}

 const meta=JSON.parse(await getSource('https://data.gov.ro/api/3/action/package_show?id=lista-furnizori'));const candidates=(meta.result?.resources||[]).map((r:any)=>{const m=String(r.name).match(/(\d{2})\.(\d{2})\.(20\d{2})/);return {...r,period:m?m[0]:'',date:m?m[3]+'-'+m[2]+'-'+m[1]:''}}).filter((r:any)=>String(r.name).toUpperCase().includes(' '+c.resource+' ')&&r.date>=new Date(Date.now()-3*365.25*86400000).toISOString().slice(0,10)).sort((a:any,b:any)=>b.date.localeCompare(a.date));const resource=candidates[0];if(!resource||new URL(resource.url).origin!=='https://data.gov.ro')throw new SourceError('Exportul CNAS recent nu este disponibil.');const bytes=await downloadResource(new URL(resource.url));return parseHealth(bytes.buffer as ArrayBuffer,kind,resource.period);
 }}};
export function parseSiruta(raw:string):Loaded{
 const lines=raw.replace(/^\uFEFF/,'').trim().split(/\r?\n/);const keys=lines.shift()!.split(';');if(!keys.includes('SIRUTA')||!keys.includes('DENLOC'))throw new SourceError('Structură SIRUTA incompatibilă.');const col=(n:string)=>keys.indexOf(n);
 const rows=lines.map(l=>l.split(';'));const counties=Object.fromEntries(rows.filter(r=>r[col('NIV')]==='1').map(r=>[r[col('JUD')],r[col('DENLOC')]]));
 const items=rows.filter(r=>r[col('NIV')]==='3').map(r=>({id:r[col('SIRUTA')],name:r[col('DENLOC')],county:counties[r[col('JUD')]]||'',details:Object.fromEntries(keys.map((k,i)=>[k,r[i]||''])),parent:r[col('SIRSUP')],postal:r[col('CODP')],environment:r[col('MED')]==='1'?'Urban':'Rural'}));if(items.length<1000)throw new SourceError('Registrul SIRUTA este incomplet.');return{data:{items,period:'Semestrul I 2026'},publishedAt:'2026'};
}
export const sirutaLoader:Loader={key:'siruta',name:'INS · SIRUTA',url:'https://data.gov.ro/dataset/siruta_s1-2026',version:'siruta.complete-fields.v2',ttl:86400,load:async()=>{const meta=JSON.parse(await getSource('https://data.gov.ro/api/3/action/package_show?id=siruta_s1-2026'));const r=meta.result?.resources?.find((r:any)=>String(r.format).toUpperCase()==='CSV');if(!r?.url?.startsWith('https://data.gov.ro/'))throw new SourceError('Exportul SIRUTA nu este disponibil.');const d=parseSiruta(await getSource(r.url));return{...d,publishedAt:r.last_modified||'2026'}}};
