import {getSource,SourceError} from './adapters';
import type {Loader,Loaded} from './types';
import {uniqueRecords,canonicalUrl} from './records';
import {feedMedia} from './media';
import {sourceText} from './text';
export const feedConfigs:Record<string,{name:string;url:string}>={munca:{name:'ANOFM',url:'https://www.anofm.ro/feed/'},stiri:{name:'Ministerul Afacerilor Interne',url:'https://www.mai.gov.ro/feed/'},sanatate:{name:'CNAS',url:'https://cnas.ro/feed/'},educatie:{name:'Ministerul Educației și Cercetării',url:'https://www.edu.ro/rss.xml'},justitie:{name:'Ministerul Justiției',url:'https://www.just.ro/feed/'},energie:{name:'Ministerul Energiei',url:'https://energie.gov.ro/feed/'},transport:{name:'TPBI',url:'https://tpbi.ro/feed/'}};
export const xmlText=sourceText;
export function parseFeed(raw:string):Loaded{
 const items=[...raw.matchAll(/<item[\s>]([\s\S]*?)<\/item>/g)].map((m,i)=>{const field=(tag:string)=>xmlText(m[1].match(new RegExp('<'+tag+'[^>]*>([\\s\\S]*?)<\\/'+tag+'>'))?.[1]||'');const title=field('title');const url=field('link');const date=field('pubDate');const summary=field('description');const content=field('content:encoded');if(!title||!/^https?:\/\//.test(url))throw new SourceError('Intrare RSS incompatibilă.');return{id:url,title,summary,content,textComplete:Boolean(content),media:feedMedia(m[1],url),url,publishedAt:Number.isFinite(Date.parse(date))?new Date(date).toISOString():null}});
 if(!items.length)throw new SourceError('Fluxul nu conține anunțuri verificabile.');return{data:{items:uniqueRecords(items,x=>canonicalUrl(x.url))},publishedAt:items[0].publishedAt};
}
export const feedLoader=(category:string):Loader=>{const c=feedConfigs[category];return{key:'feed:'+category,name:c.name,url:c.url,version:'rss2.decoded-complete-media.v7',ttl:1800,load:async()=>parseFeed(await getSource(c.url))}};
export function parseAfir(raw:string):Loaded{
 const months=['ianuarie','februarie','martie','aprilie','mai','iunie','iulie','august','septembrie','octombrie','noiembrie','decembrie'];
 const items=[...raw.matchAll(/<div class="card-body news-content">([\s\S]*?)<div class="news-border">/g)].flatMap(m=>{const part=m[1];const href=part.match(/href="(\/comunicate\/[^"<>]+)"/)?.[1];const title=part.match(/<h4[^>]*>([\s\S]*?)<\/h4>/)?.[1];const date=xmlText(part.match(/<p class="item-date[^>]*>([\s\S]*?)<\/p>/)?.[1]||'');const bits=date.match(/(\d{1,2})\s+(\S+)\s+(\d{4})/);return href&&title?[{id:href,title:xmlText(title),url:'https://www.afir.ro'+href,publishedAt:bits&&months.includes(bits[2])?`${bits[3]}-${String(months.indexOf(bits[2])+1).padStart(2,'0')}-${bits[1].padStart(2,'0')}`:null}]:[]});
 if(!items.length)throw new SourceError('Structura comunicatelor AFIR s-a schimbat.');return{data:{items:uniqueRecords(items,x=>canonicalUrl(x.url))},publishedAt:items[0]?.publishedAt||null};
}
export const afirLoader:Loader={key:'feed:agricultura',name:'AFIR',url:'https://www.afir.ro/',version:'afir.headlines.v1',ttl:3600,load:async()=>parseAfir(await getSource('https://www.afir.ro/'))};
const filmQuery=()=>'SELECT ?film ?filmLabel ?date ?directorLabel ?image WHERE { ?film wdt:P31/wdt:P279* wd:Q11424; wdt:P495 wd:Q218. OPTIONAL { ?film wdt:P577 ?date. } OPTIONAL { ?film wdt:P57 ?director. } OPTIONAL { ?film wdt:P18 ?image. } SERVICE wikibase:label { bd:serviceParam wikibase:language "ro,en". } } ORDER BY DESC(?date)';
export function parseFilms(raw:string):Loaded{const d=JSON.parse(raw);if(!Array.isArray(d.results?.bindings))throw new SourceError('Structură Wikidata incompatibilă.');const found=new Map<string,any>();for(const row of d.results.bindings){const id=row.film?.value?.match(/Q\d+$/)?.[0];if(!id||!row.filmLabel?.value)continue;const title=row.filmLabel.value;if(title===id)continue;let item=found.get(id);if(!item){item={id,title,date:row.date?.value||null,directors:[],url:'https://www.wikidata.org/wiki/'+id,media:row.image?.value?[{kind:'image',url:row.image.value.replace('http:','https:'),caption:title,sourceUrl:'https://www.wikidata.org/wiki/'+id}]:[]};found.set(id,item)}if(row.directorLabel?.value&&!item.directors.includes(row.directorLabel.value))item.directors.push(row.directorLabel.value);if(row.date?.value&&(!item.date||row.date.value<item.date))item.date=row.date.value}if(!found.size)throw new SourceError('Catalogul nu a returnat filme.');return{data:{items:[...found.values()]},publishedAt:null}}
export const filmsLoader:Loader={key:'films',name:'Wikidata · CC0',url:'https://query.wikidata.org/',version:'wikidata.films.all-years.v3',ttl:86400,load:async()=>parseFilms(await getSource('https://query.wikidata.org/sparql?'+new URLSearchParams({query:filmQuery(),format:'json'}),{headers:{Accept:'application/sparql-results+json'}}))};
