import type {Loaded} from './types';
export const currentVariables=['temperature_2m','relative_humidity_2m','apparent_temperature','is_day','precipitation','rain','showers','snowfall','weather_code','cloud_cover','pressure_msl','surface_pressure','wind_speed_10m','wind_direction_10m','wind_gusts_10m'];
export const hourlyVariables=[...currentVariables,'dew_point_2m','precipitation_probability','visibility','uv_index','uv_index_clear_sky','snow_depth','cloud_cover_low','cloud_cover_mid','cloud_cover_high','evapotranspiration','et0_fao_evapotranspiration','vapour_pressure_deficit','soil_temperature_0cm','soil_temperature_6cm','soil_temperature_18cm','soil_temperature_54cm','soil_moisture_0_to_1cm','soil_moisture_1_to_3cm','soil_moisture_3_to_9cm','soil_moisture_9_to_27cm','soil_moisture_27_to_81cm','shortwave_radiation','direct_radiation','diffuse_radiation','direct_normal_irradiance','terrestrial_radiation','sunshine_duration'];
export const dailyVariables=['weather_code','temperature_2m_max','temperature_2m_min','apparent_temperature_max','apparent_temperature_min','sunrise','sunset','daylight_duration','sunshine_duration','uv_index_max','uv_index_clear_sky_max','precipitation_sum','rain_sum','showers_sum','snowfall_sum','precipitation_hours','precipitation_probability_max','wind_speed_10m_max','wind_gusts_10m_max','wind_direction_10m_dominant','et0_fao_evapotranspiration'];
const epoch=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?new Date(v*1000).toISOString():null;
export function parseForecast(raw:string):Loaded{const d=JSON.parse(raw);if(d.error||!d.current||!epoch(d.current.time)||!d.hourly||!d.daily)throw new Error('Prognoza nu are o structură validă.');const rows=(part:any,variables:string[])=>{if(!Array.isArray(part.time)||!part.time.length)throw new Error('Lipsesc intervalele prognozei.');for(const key of variables)if(!Array.isArray(part[key])||part[key].length!==part.time.length||part[key].some((v:unknown)=>v!==null&&(typeof v!=='number'||!Number.isFinite(v))))throw new Error('Prognoza a fost transmisă incomplet.');return part.time.map((t:number,i:number)=>{const time=epoch(t);if(!time)throw new Error('Interval meteo invalid.');return{time,...Object.fromEntries(variables.map(k=>[k,(k==='sunrise'||k==='sunset')?epoch(part[k][i]):part[k][i]]))}})};for(const key of currentVariables)if(!(key in d.current)||d.current[key]!==null&&(typeof d.current[key]!=='number'||!Number.isFinite(d.current[key])))throw new Error('Condițiile meteo au câmpuri invalide.');
 // Contrazicerile interne ale sursei se semnalează, nu se repară: o zi cu
 // totalul de precipitații sub componenta de ploaie (ambele în mm, verificate
 // pe unități) primește un flag onest — valorile originale rămân neschimbate,
 // iar zăpada (cm) nu intră niciodată în comparație numerică.
 const dayRows=rows(d.daily,dailyVariables),precipitationFlags=d.daily_units?.precipitation_sum==='mm'&&d.daily_units?.rain_sum==='mm'?dayRows.flatMap((row:{time:string|null;precipitation_sum:number|null;rain_sum:number|null})=>{const total=row.precipitation_sum,rain=row.rain_sum;return typeof total==='number'&&typeof rain==='number'&&Number.isFinite(total)&&Number.isFinite(rain)&&rain-total>0.1?[{day:row.time,type:'precipitation-total-inconsistent',precipitationSum:total,rainSum:rain,unit:'mm',note:'Totalul zilnic raportat de sursă este mai mic decât componenta de ploaie; valorile originale se păstrează, fără corecție.'}]:[]}):[];
 return{publishedAt:epoch(d.current.time),data:{latitude:d.latitude,longitude:d.longitude,elevation:d.elevation,timezone:d.timezone,interval:d.current.interval,current:{...d.current,time:epoch(d.current.time)},currentUnits:d.current_units,hourly:rows(d.hourly,hourlyVariables),hourlyUnits:d.hourly_units,daily:dayRows,dailyUnits:d.daily_units,qualityFlags:precipitationFlags,attribution:'Open-Meteo · CC BY 4.0',method:'Valori calculate de modele meteorologice, distincte de observațiile măsurate la stațiile ANM.'}}}
export const forecastVersion='weather.forecast.complete.v2';
export const forecastTtl=600;
export function forecastConfig(lat:number,lon:number){lat=Math.round(lat*100)/100;lon=Math.round(lon*100)/100;return{key:`forecast:${lat}:${lon}`,name:'Open-Meteo · prognoză locală',url:'https://open-meteo.com/',version:forecastVersion,ttl:forecastTtl,requestUrl:'https://api.open-meteo.com/v1/forecast?'+new URLSearchParams({latitude:String(lat),longitude:String(lon),current:currentVariables.join(','),hourly:hourlyVariables.join(','),daily:dailyVariables.join(','),forecast_days:'7',timezone:'auto',timeformat:'unixtime',wind_speed_unit:'kmh'})}}
