const named:Record<string,string>={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' ',ensp:' ',emsp:' ',ndash:'–',mdash:'—',lsquo:'‘',rsquo:'’',ldquo:'“',rdquo:'”',hellip:'…',euro:'€',copy:'©',reg:'®',trade:'™',bull:'•',middot:'·',times:'×'};
function decodePass(text:string){return text.replace(/&#(?:x([\da-f]+)|(\d+));/gi,(whole,hex,dec)=>{const n=hex?parseInt(hex,16):Number(dec);return n>0&&n<=0x10ffff&&!(n>=0xd800&&n<=0xdfff)?String.fromCodePoint(n):whole}).replace(/&([a-z]+);/gi,(whole,name)=>named[name.toLowerCase()]??whole)}
export function decodeEntities(value:string){let text=String(value||'');for(let pass=0;pass<6;pass++){const next=decodePass(text);if(next===text)break;text=next}return text}
/** Native HTML needs one decoding pass; preserve intentionally escaped literals. */
export const decodeHtmlEntities=(value:string)=>decodePass(value);
/** Gallery widgets can carry JSON with decoded quotes inside HTML attributes in older copies. */
function stripJsonAttributes(text:string){const pattern=/\bdata-[\w:-]+\s*=\s*(["'])\s*([\[{])/g;let last=0,out='',match:RegExpExecArray|null;while((match=pattern.exec(text))){const openAt=text.lastIndexOf('<',match.index);if(openAt<0||text.lastIndexOf('>',match.index)>openAt||!/^<\/?[A-Za-z][\w:.-]*(?:\s|$)/.test(text.slice(openAt,match.index)))continue;const start=pattern.lastIndex-1,stack:string[]=[];let quote=false,escaped=false,end=-1;for(let at=start;at<text.length;at++){const c=text[at];if(quote){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')quote=false;continue}if(c==='"'){quote=true;continue}if(c==='{'||c==='[')stack.push(c);else if(c==='}'||c===']'){const open=stack.pop();if(open!==(c==='}'?'{':'['))break;if(!stack.length){end=at;break}}}if(end<0||text[end+1]!==match[1])continue;out+=text.slice(last,match.index)+match[0].slice(0,match[0].indexOf('='))+'=""';last=end+2;pattern.lastIndex=last}return out+text.slice(last)}
function stripMarkup(text:string){return stripJsonAttributes(text).replace(/<!--[\s\S]*?-->/g,'').replace(/<(?:script|style|noscript)\b[^>]*>[\s\S]*?<\/(?:script|style|noscript)>/gi,'').replace(/<\/(?:p|div|section|article|h[1-6]|ul|ol|li|tr|blockquote)>|<br\s*\/?>/gi,'\n').replace(/<li\b[^>]*>/gi,'\n• ').replace(/<\/?[A-Za-z][\w:.-]*(?=\s|\/?>)(?:"[^"]*"|'[^']*'|[^'">])*?\/?>/g,'')}
/** Remove each markup layer before decoding the next; attribute entities remain intact while tags are read. */
export function sourceText(value:unknown){let text=String(value??'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1');for(let pass=0;pass<7;pass++){const next=decodePass(stripMarkup(text));if(next===text)break;text=next}return stripMarkup(text).replace(/\r\n?/g,'\n').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
