import {env} from 'cloudflare:workers';import {createHash} from 'node:crypto';
import rawManifest from '@/public/places/manifest.json';
import {snapshotAssetPath,decodeSnapshotBytes} from '@/lib/snapshot-transport';
import {queryPlaces,type PlacesManifest,type AssetProof} from '@/lib/places-query';
export const dynamic='force-dynamic';
const manifest=rawManifest as unknown as PlacesManifest;
export async function GET(request:Request){
 const p=new URL(request.url).searchParams,category=p.get('category')||'local',query={category,photos:p.get('photos')==='true',q:p.get('q')||'',sub:p.get('sub')||'',contact:p.get('contact')||'',scope:p.get('scope')||'all',lat:p.has('lat')?Number(p.get('lat')):NaN,lon:p.has('lon')?Number(p.get('lon')):NaN,radius:Number(p.get('radius')||15),sort:p.get('sort')||'name',page:Number(p.get('page')||0),pageSize:p.has('pageSize')?Number(p.get('pageSize')):18};
 if(!manifest.indices[category==='local'?'local-all':category]||query.q.length>200||query.sub.length>200||!['','phone','email','website','address','openingHours'].includes(query.contact)||!['all','nearby'].includes(query.scope)||!['name','recent','distance'].includes(query.sort)||!Number.isInteger(query.page)||query.page<0||query.page>100000||query.radius<1||query.radius>100||!Number.isInteger(query.pageSize)||query.pageSize<1||query.pageSize>200||((query.scope==='nearby'||query.sort==='distance')&&(!Number.isFinite(query.lat)||!Number.isFinite(query.lon)||Math.abs(query.lat)>90||Math.abs(query.lon)>180)))return Response.json({error:'Alege o localitate și filtre valide.'},{status:400});
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);
 try{const read=async(proof:AssetProof)=>{const req=new Request(new URL(snapshotAssetPath('/places/'+proof.file),request.url),{signal:controller.signal}),response=env.ASSETS?await env.ASSETS.fetch(req):await fetch(req);if(!response.ok)throw Error('Inventarul nu poate fi citit acum.');const bytes=decodeSnapshotBytes(await response.arrayBuffer());if(bytes.byteLength!==proof.bytes||createHash('sha256').update(new Uint8Array(bytes)).digest('hex')!==proof.sha256)throw Error('Copia nu a trecut verificarea integralității.');return JSON.parse(new TextDecoder().decode(bytes))};const data=await queryPlaces(manifest,query,read);return Response.json({key:'places:'+category,name:'OpenStreetMap · inventarul național',url:manifest.sourceUrl,adapterVersion:manifest.schema,status:'cached',data,publishedAt:manifest.dataAsOf,lastSuccessAt:manifest.fetchedAt,lastAttemptAt:null,nextAttemptAt:null,error:null,ttlSeconds:86400},{headers:{'Cache-Control':'public, max-age=300'}})}catch(e){return Response.json({error:controller.signal.aborted?'Căutarea nu a răspuns la timp. Restrânge filtrele sau reîncearcă.':e instanceof Error?e.message:'Căutarea nu poate fi încărcată acum.'},{status:503})}finally{clearTimeout(timer)}
}
