'use client';
import {useState} from 'react';
import {Image as ImageIcon,Maximize2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import manifest from '@/public/media/category-manifest.json';
import illustrations from '@/public/media/category-illustrations.json';
const mapping:Record<string,string>={local:'localities',bani:'money-economy',firme:'companies',mediu:'environment-weather',transport:'transport',sanatate:'health',educatie:'education',cultura:'culture',munca:'work',justitie:'justice',energie:'energy',agricultura:'agriculture',filme:'cinema',stiri:'institutional-news'};
export function CategoryPhoto({id,cover=false}:{id:string;cover?:boolean}){
 const artwork=illustrations.find(m=>m.id===id)||illustrations.find(m=>m.id===(id==='povesti'?'cultura':id==='vreme'?'mediu':id)),items=manifest.filter(m=>m.category===mapping[id==='povesti'?'cultura':id==='vreme'?'mediu':id]),[selected,setSelected]=useState<(typeof manifest)[number]|null>(null);if(!items.length)return null;
 if(cover)return artwork?<figure className="category-cover-frame"><img className="category-cover" src={'/media/'+artwork.file} alt={artwork.caption} loading="lazy" width={artwork.width} height={artwork.height}/><figcaption>Ilustrație AI</figcaption></figure>:null;
 return <><div className="category-photo-grid">{items.map(item=><figure className="category-banner" key={item.file}><button type="button" className="category-photo-frame" onClick={()=>setSelected(item)} aria-label={'Vezi fotografia: '+item.caption}><img data-parallax src={'/media/'+item.file} alt={item.caption} loading="lazy" width={1200} height={800}/><span><Maximize2 size={17}/>Vezi fotografia</span></button><figcaption><span><ImageIcon size={16}/>{item.caption} · fotografie ilustrativă</span><small>{item.credit} · {item.license}. Miniatură decupată și colorizată pentru temă. <a href={item.sourceUrl} target="_blank" rel="noreferrer">Proveniență</a> · <a href={item.licenseUrl} target="_blank" rel="noreferrer">Licență</a></small></figcaption></figure>)}</div><Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="v2 photo-dialog reader-dialog"><DialogHeader><DialogTitle>{selected?.caption}</DialogTitle><DialogDescription>Fotografie ilustrativă · {selected?.credit}</DialogDescription></DialogHeader>{selected&&<div className="reader-body"><img className="category-full-photo" src={'/media/'+selected.file} alt={selected.caption}/><p>{selected.credit} · {selected.license} · redimensionată și convertită în WebP.</p><a href={selected.sourceUrl} target="_blank" rel="noreferrer">Proveniența fotografiei</a> · <a href={selected.licenseUrl} target="_blank" rel="noreferrer">Licența de reutilizare</a></div>}</DialogContent></Dialog></>;
}
