'use client';
import {SearchInput} from './search-input';
import {Film,Newspaper,Zap,Sprout,MapPin,Coins,Building2,Leaf,TrainFront,HeartPulse,GraduationCap,Landmark,BriefcaseBusiness,Scale,Database,Layers,BookOpen,CloudSun,Search} from 'lucide-react';
import {useState} from 'react';import {Input} from '@/components/ui/input';import {topicGroups,topicGroup,topicSections} from '@/lib/dashboard-topics';import {normalizeSearch} from '@/lib/live/query';
import {Button} from '@/components/ui/button';
import {AssetExport} from './export-actions';
import {domains} from './v2-model';
import {CategoryPhoto} from './category-photo';
const icons:any={Film,Newspaper,Zap,Sprout,MapPin,Coins,Building2,Leaf,TrainFront,HeartPulse,GraduationCap,Landmark,BriefcaseBusiness,Scale,BookOpen,CloudSun};
/** Shared by Home and Dashboard: every topic and the uncategorized catalog remain reachable. */
export function CategoryDirectory({onSelect,onCatalog}:{onSelect:(id:string)=>void;onCatalog:(category:string)=>void}){const [group,setGroup]=useState('all'),[q,setQ]=useState('');const visible=domains.filter(d=>(group==='all'||topicGroup[d.id]===group)&&normalizeSearch(d.name+' '+d.intro+' '+(topicSections[d.id]||[]).map(s=>s.label).join(' ')).includes(normalizeSearch(q)));return <section className="category-directory"><div className="category-toolbar"><div className="chip-row">{topicGroups.map(g=><button key={g.id} type="button" aria-pressed={group===g.id} className={group===g.id?'selected':''} onClick={()=>setGroup(g.id)}>{g.label}</button>)}</div><label className="category-search"><span className="control-label"><Search size={18}/></span><SearchInput value={q} onValueChange={value=>setQ(value)} aria-label="Caută categorii și subcategorii" placeholder="Caută un domeniu sau un serviciu"/></label></div><div className="domain-grid">{visible.map(domain=>{const Icon=icons[domain.icon];return <button type="button" className="domain-card" key={domain.id} onClick={()=>onSelect(domain.id)} aria-label={'Explorează '+domain.name}><CategoryPhoto id={domain.id} cover/><span className="domain-card-content"><Icon aria-hidden="true"/><h3>{domain.name}</h3><p>{domain.intro}</p><span className="category-section-preview">{(topicSections[domain.id]||[]).slice(0,3).map(s=>s.label).join(' · ')}</span><span className="category-card-action">Explorează domeniul</span></span></button>})}<button type="button" className="domain-card category-other" onClick={()=>onCatalog('alte')}><span className="category-other-visual"><Database size={48}/><Layers size={28}/></span><span className="domain-card-content"><Database aria-hidden="true"/><h3>Alte date publice</h3><p>Seturile care nu au o încadrare în domeniile de mai sus: toate fișele și resursele lor.</p><span className="category-card-action">Explorează seturile</span></span></button></div><div className="category-directory-footer"><div><p>Ilustrații reprezentative și fotografii atribuite</p><AssetExport path="/media/category-manifest.json" title="Surse și licențe"/></div><Button type="button" variant="outline" onClick={()=>onCatalog('')}><Layers size={18}/>Toate seturile de date</Button></div></section>}
