'use client';
import {useLocation} from './location';
import {GeographicScopeField,useGeographicScope,useLocationState} from './location-scope';
import {classifyGeography,matchesGeography,readGeographicContext,geographicParams} from '@/lib/geographic-scope';
import {createSearchIndex,searchIndex,compareNames} from '@/lib/live/query';
import {DraftForm} from './draft-form';
import {SelectField} from './select-field';
import {SearchInput} from './search-input';
import {fetchWithServerRetry} from '@/lib/http-retry.mjs';
import {memo,useEffect,useMemo,useRef,useState} from 'react';import {Search,RefreshCw,Download,Scale,CalendarDays} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Freshness,dateText} from './live-data';import {ExportActions} from './export-actions';
import {Pagination} from './pagination';import {countText,paginate,matchesQuery,normalizeSearch} from '@/lib/live/query';import type {SourceState} from '@/lib/live/types';
import institutions from '@/public/courts/institutions.json';
import {courtSearchPlan,normalizeCourtNumber,type CourtQuery,type CourtNumberScope} from '@/lib/court-query';
import {buildCourtHistories,type CourtHistory} from '@/lib/court-history';
import {upstreamDiacriticLoss,DIACRITIC_LOSS_NOTE,ACT_LINKS_ABSENCE_NOTE} from '@/lib/court-history';
import {CourtHistoryPanel} from './court-history-panel';
const courtRecordId=(id:string)=>'court-record-'+id.replace(/[^a-zA-Z0-9_-]/g,'-');
type Query=CourtQuery&{numberScope:CourtNumberScope};
const blank:Query={number:'',name:'',subject:'',institution:'',from:'',to:'',numberScope:'all'};
const withDiacriticsNote=(text:string)=>upstreamDiacriticLoss(text)?text+'\n\n'+DIACRITIC_LOSS_NOTE:text;
const caseText=(item:any)=>['Fișa publică a dosarului '+item.number,'Instanță: '+item.courtLabel,'Materie: '+item.category,'Obiect: '+item.subject,'Stadiu: '+item.stage,'Secție: '+item.department,'Înregistrat: '+dateText(item.date),'Modificat: '+dateText(item.modified),'PĂRȚI PUBLICATE',...item.parties.map((p:any)=>p.name+' — '+p.role),'ȘEDINȚE ȘI SOLUȚII PE SCURT',...item.hearings.map((h:any)=>[dateText(h.date),h.time,h.panel,h.result,h.summary,h.document+' '+h.documentNumber,'Data pronunțării: '+dateText(h.pronouncementDate),'Data documentului: '+dateText(h.documentDate)].join('\n')),'CĂI DE ATAC',...item.appeals.map((a:any)=>[dateText(a.date),a.type,a.party].join(' · ')),...(upstreamDiacriticLoss(JSON.stringify(item))?[DIACRITIC_LOSS_NOTE]:[]),'Sursa: https://portal.just.ro/SitePages/dosare.aspx','Această fișă cuprinde datele și soluțiile pe scurt din portal. Nu reprezintă textul integral al hotărârii.'].join('\n\n');
const CourtCase=memo(function CourtCase({item,expanded,onExpandedChange}:{item:any;expanded?:boolean;onExpandedChange?:(value:boolean)=>void}){const [localOpen,setLocalOpen]=useState(false),open=expanded??localOpen,setOpen=(update:boolean|((value:boolean)=>boolean))=>{const next=typeof update==='function'?update(open):update;if(onExpandedChange)onExpandedChange(next);else setLocalOpen(next)},lawyers=item.parties.filter((p:any)=>/avocat|apărător|aparator/i.test(p.role));return <article className="court-case" id={courtRecordId(item.id)} tabIndex={-1}><div className="panel-top"><div><span className="kicker">{item.courtLabel}</span><h3>Dosar {item.number}</h3><p>{item.category} · {item.subject||'Obiect neprecizat'}</p><p>{item.stage||'Stadiu neprecizat'} · {item.department||'Secție neprecizată'}</p><p>{countText(item.hearings.length,'ședință publicată','ședințe publicate')} · Înregistrat: {dateText(item.date)} · Modificat: {dateText(item.modified)}</p></div><Button variant="outline" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{open?'Restrânge detaliile':'Vezi toate detaliile'}</Button></div>{open&&<><dl className="reader-facts">{[['Instanță',item.courtLabel],['Secție',item.department],['Materie',item.category],['Înregistrat',dateText(item.date)],['Ultima modificare indicată',dateText(item.modified)],['Număr vechi',item.oldNumber]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Nefurnizat de sursă'}</dd></div>)}</dl><div className="entity-detail-actions"><ExportActions input={{title:"Fișa publică a dosarului "+item.number,text:caseText(item)}} formats={["pdf"]} label="Descarcă fișa publică"/><ExportActions input={{title:"Dosar "+item.number,data:item,subtitle:item.courtLabel}} formats={["csv","xlsx"]} label="Toate datele dosarului"/></div>
 <Tabs defaultValue="hearings"><TabsList className="domain-subcategories"><TabsTrigger value="hearings">Ședințe și soluții ({item.hearings.length})</TabsTrigger><TabsTrigger value="parties">Părți și calități</TabsTrigger><TabsTrigger value="lawyers">Avocați</TabsTrigger><TabsTrigger value="appeals">Căi de atac</TabsTrigger><TabsTrigger value="documents">Hotărâri și documente</TabsTrigger></TabsList>
 <TabsContent value="hearings"><div className="court-timeline">{item.hearings.map((h:any,i:number)=><article key={i}><span><CalendarDays size={17}/>{dateText(h.date)} · {h.time}</span><h4>{h.result||'Soluție neprecizată'}</h4><p className="reading-text">{h.summary||'Sursa nu a furnizat o soluție pe scurt.'}</p>{h.pronouncementDate&&<p>Pronunțare: {dateText(h.pronouncementDate)}</p>}<p>Complet: {h.panel||'Neprecizat'} · {h.document} {h.documentNumber} · {dateText(h.documentDate)}</p>{h.summary&&<ExportActions input={{title:"Soluție pe scurt · dosar "+item.number,text:withDiacriticsNote(h.summary),subtitle:item.courtLabel+" · "+dateText(h.date)+" · Document indicat: "+h.document+" "+h.documentNumber+". Portalul instanțelor. Textul integral al hotărârii nu este inclus."}} formats={["pdf"]} label="Descarcă soluția pe scurt"/>}</article>)}{!item.hearings.length&&<p>Nu sunt ședințe în răspunsul public.</p>}</div></TabsContent>
 <TabsContent value="parties"><div className="table-scroll"><table className="facts-table"><thead><tr><th>Parte publicată</th><th>Calitate în acest dosar</th></tr></thead><tbody>{item.parties.map((p:any,i:number)=><tr key={i}><td>{p.name}</td><td>{p.role}</td></tr>)}</tbody></table></div>{!item.parties.length&&<p>Sursa nu a publicat părți pentru acest dosar.</p>}{normalizeSearch(item.category).includes('penal')&&<p className="field-help">Calitatea de inculpat este cea publicată în dosar; o condamnare se stabilește din hotărârea instanței.</p>}</TabsContent>
 <TabsContent value="lawyers">{lawyers.map((p:any,i:number)=><p key={i}>{p.name} · {p.role}</p>)}{!lawyers.length&&<p>Serviciul public nu a transmis un avocat identificabil pentru acest dosar. Reprezentarea poate apărea în documentele hotărârii sau în dosarul electronic accesibil persoanelor autorizate.</p>}</TabsContent>
 <TabsContent value="appeals">{item.appeals.map((a:any,i:number)=><p key={i}>{dateText(a.date)} · {a.type} · {a.party}</p>)}{!item.appeals.length&&<p>Nu sunt căi de atac în răspunsul public.</p>}</TabsContent>
 <TabsContent value="documents"><h4>Documente indicate de instanță</h4>{item.hearings.filter((h:any)=>h.document||h.documentNumber).map((h:any,i:number)=><p key={i}>{h.document||'Document'} {h.documentNumber} · {dateText(h.documentDate)}</p>)}<p>Portalul a transmis identificatorii documentelor și soluțiile pe scurt, fără fișierul hotărârii. Hotărârile din ReJust sunt publicate în format anonimizat; potrivirea cu o persoană nu este confirmată automat.</p><p className="field-help">{ACT_LINKS_ABSENCE_NOTE}</p><div className="entity-detail-actions"><a className="text-link" href="https://www.rejust.ro/" target="_blank" rel="noreferrer">Jurisprudența publică ReJust</a><a className="text-link" href="https://registratura.rejust.ro/eliberare-copie-legalizata-a-unei-hotarari-judecatoresti" target="_blank" rel="noreferrer">Solicită copia hotărârii de la instanță</a></div></TabsContent></Tabs></>}</article>});
export function Courts({initialNumber=''}:{initialNumber?:string}={}){const geo=useLocation(),[geoScope,setGeoScope]=useGeographicScope(),context=readGeographicContext(new URLSearchParams(geographicParams(geo,geoScope)))!,localInstitutions=institutions.items.filter(c=>matchesGeography(classifyGeography({title:c.label+' '+c.id.replace(/([a-z])([A-Z])/g,'$1 $2')}),context)),initialInstitution=context.active?localInstitutions.find(c=>/^Judecatoria/.test(c.id))?.id||localInstitutions[0]?.id||'':'',[query,setQuery]=useLocationState<Query>(()=>({...blank,number:initialNumber,institution:initialInstitution})),[last,setLast]=useLocationState<Query|null>(null),[source,setSource]=useLocationState<SourceState|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[category,setCategory]=useState(''),[filter,setFilter]=useState(''),[sort,setSort]=useState('recent'),[page,setPage]=useLocationState(0),[expandedIds,setExpandedIds]=useState<string[]>([]);const pendingScroll=useRef<string|null>(null);const controller=useRef<AbortController|null>(null),serial=useRef(0);
 const lastQuery=useRef<Query|null>(null);
 useEffect(()=>()=>{serial.current++;controller.current?.abort()},[]);
 const search=async(q:Query)=>{if(!courtSearchPlan(q,q.numberScope).followsNumber&&context.active&&!localInstitutions.some(c=>c.id===q.institution)){setError('Alege o instanță din zona activă sau selectează Toată România.');return}controller.current?.abort();const ac=new AbortController(),n=++serial.current;controller.current=ac;lastQuery.current=q;setLast(q);setSource(null);setBusy(true);setError('');setPage(0);setExpandedIds([]);pendingScroll.current=null;if(courtSearchPlan(q,q.numberScope).followsNumber){setCategory('');setFilter('')}let settled=false;const timeout=setTimeout(()=>{if(serial.current!==n||settled)return;settled=true;ac.abort();setBusy(false);setError('Portalul nu a răspuns la timp. Reîncearcă sau consultă portalul oficial.')},30000);try{const r=await fetchWithServerRetry('/api/legal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'court',...q,...geographicParams(geo,geoScope)}),signal:ac.signal},{retryPost:true});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Interogarea nu a reușit.');if(serial.current===n&&!settled)setSource(d)}catch(e){if(serial.current===n&&!settled)setError(e instanceof Error?e.message:'Dosarele nu pot fi încărcate acum.')}finally{clearTimeout(timeout);settled=true;if(serial.current===n)setBusy(false)}};
 useEffect(()=>{serial.current++;controller.current?.abort();setSource(null);setBusy(false);setError('');const prior=lastQuery.current;const next={...(prior||query),institution:initialInstitution};setQuery(next);if(prior&&(courtSearchPlan(next,next.numberScope).followsNumber||!context.active||initialInstitution))void search(next)},[geo.key,geoScope]);
 const index=useMemo(()=>createSearchIndex<any>(source?.data?.items||[]),[source]);const rows=useMemo(()=>searchIndex(index,filter).filter((r:any)=>(!category||normalizeSearch(r.category).includes(category))&&(source?.data?.searchScope==='number-all-courts'||!context.active||localInstitutions.some(c=>c.id===r.court))).sort((a:any,b:any)=>sort==='court'?compareNames(a.courtLabel,b.courtLabel):sort==='number'?compareNames(a.number,b.number):String(b.modified||b.date).localeCompare(String(a.modified||a.date))),[index,filter,category,sort,geo.key,geoScope] );
 const histories=useMemo<CourtHistory[]>(()=>source?.data?.caseHistories||buildCourtHistories(source?.data?.items||[]),[source]);
 const groups=useMemo(()=>{const order=new Map<string,number>();rows.forEach((item:any)=>{const number=normalizeCourtNumber(item.number);if(!order.has(number))order.set(number,order.size)});const byId=new Map<string,any>((source?.data?.items||[]).map((item:any)=>[item.id,item]));return histories.filter(history=>order.has(history.number)||!filter&&!category&&!history.recordIds.length).sort((a,b)=>(order.get(a.number)??0)-(order.get(b.number)??0)).map(history=>({history,records:history.stages.flatMap(stage=>stage.recordIds).map(id=>byId.get(id)).filter(Boolean)}))},[histories,rows,source,filter,category]),result=paginate(groups,page,12);
 useEffect(()=>{const id=pendingScroll.current;if(!id||typeof document==='undefined')return;pendingScroll.current=null;const element=document.getElementById(courtRecordId(id));element?.scrollIntoView({block:'start',behavior:'smooth'});element?.focus({preventScroll:true})},[expandedIds,result.page,source]);
 const showRecord=(id:string)=>{pendingScroll.current=id;setExpandedIds(ids=>ids.includes(id)?[...ids]:[...ids,id])};
 const searchNumber=(number:string)=>{const next={...blank,number};setQuery(next);void search(next)};
 return <section className="legal-section"><div className="panel-top"><div><span className="kicker">PORTALUL INSTANȚELOR</span><h2>Dosare, părți și soluții publice</h2><p>Caută după nume, număr sau obiect. Deschide fiecare fișă pentru părțile, ședințele și căile de atac transmise. Parcursul leagă fondul, apelul și recursul confirmate. Poți deschide fișele și verifica trimiterile oficiale între dosare.</p></div><Scale size={30}/></div><GeographicScopeField value={geoScope} onChange={setGeoScope}/><DraftForm className="court-search-form" value={query} onSearch={query=>{setQuery(query);void search(query)}}>{(query,setQuery)=><>{query.number&&<><label><span className="control-label">Căutare după număr</span><SelectField value={query.numberScope} onChange={e=>setQuery(q=>({...q,numberScope:e.target.value as CourtNumberScope}))}><option value="all">Toate instanțele și stadiile</option><option value="filtered">În filtrele alese</option></SelectField></label><p className="field-help">{query.numberScope==='all'?'Numărul este căutat la toate instanțele, indiferent de locație. Sunt păstrate toate fișele primite pentru acest număr.':'Instanța, locația și celelalte filtre pot exclude alte fișe ale aceluiași dosar.'}</p></>}<div className="entity-filters">{[['number','Număr dosar','număr/instanță/an'],['name','Nume parte','Nume și prenume sau persoană juridică'],['subject','Obiect dosar','De exemplu: furt, contestație, pretenții']].map(([id,label,placeholder])=><label key={id}><span className="control-label">{label}</span><Input disabled={id!=='number'&&courtSearchPlan(query,query.numberScope).followsNumber} value={query[id as keyof Query]} onChange={e=>setQuery(q=>({...q,[id]:e.target.value}))} placeholder={placeholder} maxLength={id==='number'?50:160}/></label>)}<label><span className="control-label">Instanță</span><SelectField disabled={courtSearchPlan(query,query.numberScope).followsNumber} value={courtSearchPlan(query,query.numberScope).followsNumber?'':query.institution} onChange={e=>setQuery(q=>({...q,institution:e.target.value}))}><option value="">{courtSearchPlan(query,query.numberScope).followsNumber?'Toate instanțele':context.active?'Alege o instanță locală':'Toate instanțele'}</option>{localInstitutions.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</SelectField></label><label><span className="control-label">Înregistrat de la</span><Input disabled={courtSearchPlan(query,query.numberScope).followsNumber} type="date" value={query.from} onChange={e=>setQuery(q=>({...q,from:e.target.value}))}/></label><label><span className="control-label">Până la</span><Input disabled={courtSearchPlan(query,query.numberScope).followsNumber} type="date" value={query.to} onChange={e=>setQuery(q=>({...q,to:e.target.value}))}/></label></div><Button disabled={busy}><Search size={17}/>{busy?'Se interoghează portalul…':'Caută dosare'}</Button></>}</DraftForm>
 <div className="entity-filters"><label><span className="control-label">Materie</span><SelectField value={category} onChange={e=>{setCategory(e.target.value);setPage(0)}}><option value="">Toate materiile</option><option value="penal">Dosare penale</option><option value="civil">Dosare civile</option><option value="comercial">Comercial</option><option value="administrativ">Contencios administrativ</option><option value="munca">Litigii de muncă</option></SelectField></label><label><span className="control-label">Caută în toate detaliile primite</span><SearchInput value={filter} onValueChange={value=>{setFilter(value);setPage(0)}} placeholder="Parte, soluție, complet, document…" maxLength={200}/></label><label><span className="control-label">Ordonare</span><SelectField value={sort} onChange={e=>{setSort(e.target.value);setPage(0)}}><option value="recent">Ultima modificare</option><option value="court">Instanță</option><option value="number">Număr dosar</option></SelectField></label></div>
 {busy&&<p role="status">Se verifică fișele și ședințele din sursa oficială…</p>}{(error||source?.status==='unavailable')&&<div className="live-error" role="alert"><p>{error||source?.error}</p>{last&&<Button variant="outline" onClick={()=>void search(last)}><RefreshCw size={16}/>Reîncearcă</Button>}</div>}{source&&<Freshness source={source}/>}{source?.data?.referenceLookupAvailable===false&&<p className="source-warning">Confirmările păstrate din alte dosare nu pot fi citite acum. Sunt afișate confirmările disponibile; reîncearcă pentru celelalte.</p>}{source?.data?.limitReached&&<p className="source-warning">Portalul a atins limita de 1.000 de rezultate. Restrânge numele, instanța sau intervalul pentru a obține un răspuns mai precis. Filtrul de materie se aplică răspunsului primit.</p>}{source?.data&&<><p>{countText(result.total,'dosar în filtrele alese','dosare în filtrele alese')} · {countText(groups.reduce((total,group)=>total+group.records.length,0),'fișă disponibilă','fișe disponibile')} · {countText(groups.reduce((total,group)=>total+group.records.reduce((n:number,item:any)=>n+item.hearings.length,0),0),'ședință','ședințe')} · {countText(source.data.items.length,'fișă primită din portal','fișe primite din portal')}</p><p className="field-help">{source.data.note}</p><a className="text-link" href="https://portal.just.ro/SitePages/dosare.aspx" target="_blank" rel="noreferrer">Verifică dosarul în portalul oficial</a><div className="court-results">{result.items.map(group=><div className="court-case-group" key={group.history.number}><CourtHistoryPanel history={group.history} onOpenRecord={showRecord} onSearchNumber={searchNumber}/>{group.records.map((item:any)=><CourtCase key={item.id} item={item} expanded={expandedIds.includes(item.id)} onExpandedChange={value=>setExpandedIds(ids=>value?[...ids.filter(id=>id!==item.id),item.id]:ids.filter(id=>id!==item.id))}/>)}</div>)}</div>{!result.items.length&&<p className="live-empty">Nu sunt rezultate pentru aceste criterii în răspunsul portalului.</p>}<Pagination page={result.page} pages={result.pages} total={result.total} onPage={setPage}/><p className="field-help">Numele identice pot aparține unor persoane diferite. Verifică numărul, instanța și calitatea publicată. Data ultimei preluări apare separat de data dosarului.</p></>}</section>;
}
