'use client';
import {fetchWithServerRetry} from '@/lib/http-retry.mjs';
import React,{useCallback,useEffect,useState,useRef,useMemo} from 'react';
import {RefreshCw,ExternalLink,Search,AlertCircle,Database,MapPin,Film,Newspaper,Zap} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';
import {DataChart} from './v2-charts';import {format,norm} from './v2-model';
import {publicSourceLink} from '@/lib/live/public-source';
import {displaySourceDate} from '@/lib/live/date';import seeds from '@/lib/live/seed.json';import {DatasetReader,ContentReader,EmbeddedMap} from './experience';import {useLocation,distanceKm} from './location';
import {uniqueRecords,canonicalUrl} from '@/lib/live/records';
import {useSource} from './use-source';
export {useSource} from './use-source';
import type {LiveBundle,SourceState} from '@/lib/live/types';
export const dateText=displaySourceDate;
function seedState(key:string,name:string,url:string):SourceState{const s=(seeds as any)[key];return{key,name,url,adapterVersion:'copie verificată',status:'stale',data:s?.data||null,publishedAt:s?.publishedAt||null,lastSuccessAt:s?.fetchedAt||null,lastAttemptAt:null,nextAttemptAt:null,error:null,ttlSeconds:0}}
const initial:LiveBundle={bnr:seedState('bnr','BNR','https://curs.bnr.ro/nbrfxrates10days.xml'),weather:seedState('weather','ANM','https://www.meteoromania.ro/'),company:seedState('company:427282','ANAF','https://webservicesp.anaf.ro/bilant'),catalog:seedState('catalog:::0','data.gov.ro','https://data.gov.ro/'),servedAt:''};
export function useLiveData(){const [data,setData]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');const refresh=useCallback(async()=>{setBusy(true);try{const r=await fetchWithServerRetry('/api/live',{cache:'no-store'});if(!r.ok)throw Error();const d:any=await r.json();if(!d.bnr||!d.weather||!d.company)throw Error();setData(d);setError('')}catch{setError('Verificarea surselor nu a reușit. Datele ultimei copii rămân vizibile.')}finally{setBusy(false)}},[]);useEffect(()=>{refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh()},60000);const focus=()=>refresh();window.addEventListener('online',focus);return()=>{clearInterval(timer);window.removeEventListener('online',focus)}},[refresh]);return{data,busy,error,refresh}}
export function Freshness({source,loading=false,documentUrl}:{source?:SourceState|null;loading?:boolean;documentUrl?:string}){if(!source)return <div className="live-freshness" role="status">{loading?'Se încarcă răspunsul sursei…':'Nu avem încă un răspuns valid pentru această încărcare.'}</div>;const link=publicSourceLink(source.url,documentUrl);return <div className={'live-freshness '+(source.status==='stale'||source.status==='unavailable'?'source-warning':'')}><div><span className="source-chip">{loading?'Se verifică':source.status==='unavailable'?'Indisponibil':source.status==='stale'?'Ultima copie disponibilă':'Sursă verificată'}</span><strong>{source.name}</strong>{link.url&&<a href={link.url} target="_blank" rel="noreferrer">{link.label} <ExternalLink size={13}/></a>}</div><p>Data informației: <b>{dateText(source.publishedAt)}</b> · Ultima preluare validă: <b>{dateText(source.lastSuccessAt)}</b></p>{source.error&&<p role="status">{source.error}{source.nextAttemptAt&&<> Reîncercare după {dateText(source.nextAttemptAt)}.</>}</p>}</div>}
function LoadState({busy,error,retry}:{busy:boolean;error:string;retry:()=>void}){return busy?<div className="live-loading" role="status"><RefreshCw size={18} className="spin"/>Căutăm informațiile la sursă…</div>:error?<div className="live-error" role="alert"><AlertCircle size={20}/><p>{error}</p><Button variant="outline" onClick={retry}>Reîncearcă</Button></div>:null}
export {LiveCatalog} from './catalog-workspace';
export {WeatherStations} from './weather-workspace';
export function EnergyCalculator(){const [kwh,setKwh]=useState(''),[price,setPrice]=useState('');const valid=kwh!==''&&price!==''&&Number(kwh)>=0&&Number(price)>=0&&Number.isFinite(Number(kwh)*Number(price));return <section className="live-section energy-calculator"><div><span className="kicker">FACTURA TA, PE ÎNȚELES</span><h2>Calculează costul consumului</h2><p>Introdu consumul măsurat și prețul final din oferta sau factura ta. Nu presupunem un tarif.</p><a href="https://posf.ro/" target="_blank" rel="noreferrer">Comparatorul oficial ANRE <ExternalLink size={15}/></a></div><div><label><span className="control-label">Consum în kWh</span><Input inputMode="decimal" type="number" min="0" value={kwh} onChange={e=>setKwh(e.target.value)}/></label><label><span className="control-label">Preț final în RON/kWh</span><Input inputMode="decimal" type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><strong className="energy-result">{valid?format(Number(kwh)*Number(price),2):'—'} RON</strong><small>Calcul din valorile tale. Nu include abonamente sau alte costuri fixe.</small></div></section>}
export function SourceOverview({data,refresh,busy}:{data:LiveBundle;refresh:()=>void;busy:boolean}){return <section className="live-section"><div className="panel-top"><h2>Starea surselor conectate</h2><Button variant="outline" onClick={refresh} disabled={busy}><RefreshCw size={16}/>{busy?'Se verifică…':'Verifică din nou'}</Button></div><p>Data publicației și momentul preluării sunt păstrate separat. La o eroare, ultima copie validă rămâne disponibilă și reîncercarea respectă pauza cerută de sursă.</p>{[data.bnr,data.weather,data.company,data.catalog].map(s=><Freshness source={s} key={s.key} loading={busy}/>)}</section>}

export {FeedCards,RecordBrowser,LocalitySearch,TransportSearch} from './record-workspace';
