'use client';
import {useEffect,useRef,useState} from 'react';
import type {Map as LeafletMap,LayerGroup,LatLngExpression} from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {bearingText,speedText,occupancyText} from '@/lib/transit-view';
export type MapPoint={id:string;name:string;lat:number;lon:number;description?:string;vehicle?:boolean;bearing?:number|null;speed?:number|null;occupancy?:string|null;occupancyPercentage?:number|null};
const emptyPaths:{lat:number;lon:number}[][]=[];
const escapeHtml=(text:string)=>text.replace(/[&<>"']/g,ch=>({'&':'&','<':'<','>':'>','"':'"',"'":'&#39;'})[ch] as string);
export function PublicMap({points,paths=emptyPaths,viewKey='map'}:{points:MapPoint[];paths?:{lat:number;lon:number}[][];viewKey?:string}){
 const element=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),layers=useRef<LayerGroup|null>(null),lastView=useRef(''),[ready,setReady]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false,frame=0;let observer:ResizeObserver|undefined;let owned:LeafletMap|undefined;import('leaflet').then(L=>{if(cancelled||!element.current)return;const m=L.map(element.current,{scrollWheelZoom:false,preferCanvas:true,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false}).setView([45.9,25],6);owned=m;map.current=m;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a>'}).addTo(m);layers.current=L.layerGroup().addTo(m);observer=new ResizeObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(!cancelled)m.invalidateSize({pan:false})})});observer.observe(element.current);setReady(true)}).catch(()=>{if(!cancelled)setError('Harta nu poate fi încărcată acum. Adresele și coordonatele rămân disponibile.');});return()=>{cancelled=true;observer?.disconnect();cancelAnimationFrame(frame);layers.current?.clearLayers();owned?.remove();map.current=null;layers.current=null}},[]);
 useEffect(()=>{if(!ready||!map.current||!layers.current)return;let cancelled=false;import('leaflet').then(L=>{if(cancelled||!map.current||!layers.current)return;layers.current.clearLayers();const bounds:LatLngExpression[]=[];for(const path of paths){const line=path.filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)).map(x=>[x.lat,x.lon] as [number,number]);if(line.length>1){L.polyline(line,{color:'#0877ed',weight:4,opacity:.85}).addTo(layers.current);bounds.push(...line)}}for(const p of points){if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon))continue;const telemetry=p.vehicle?[bearingText(p.bearing),speedText(p.speed),occupancyText(p.occupancy,p.occupancyPercentage)].filter(Boolean).join(' · '):'';const text=document.createElement('div'),title=document.createElement('strong');title.textContent=p.name;text.appendChild(title);if(p.description){const info=document.createElement('p');info.textContent=p.description;text.appendChild(info)}if(telemetry){const live=document.createElement('p');live.textContent=telemetry;text.appendChild(live)}const heading=p.vehicle&&p.bearing!==null&&p.bearing!==undefined?Number(p.bearing):NaN;if(p.vehicle&&Number.isFinite(heading)){const label=[p.name,telemetry].filter(Boolean).join(' · ');const degrees=((heading%360)+360)%360;const icon=L.divIcon({className:'',iconSize:[28,28],iconAnchor:[14,14],html:'<div role="img" aria-label="'+escapeHtml(label)+'"><svg viewBox="0 0 28 28" width="28" height="28" aria-hidden="true" focusable="false"><g transform="rotate('+degrees+' 14 14)"><path d="M14 2.5 L21.5 23 L14 19 L6.5 23 Z" fill="#0877ed" stroke="#ffffff" stroke-width="2" stroke-linejoin="round"/></g></svg></div>'});L.marker([p.lat,p.lon],{icon,title:label}).bindPopup(text).addTo(layers.current)}else{L.circleMarker([p.lat,p.lon],{radius:p.vehicle?9:6,color:p.vehicle?'#ffffff':'#0a3975',weight:2,fillColor:p.vehicle?'#0877ed':'#ffffff',fillOpacity:1}).bindPopup(text).addTo(layers.current)}bounds.push([p.lat,p.lon])}if(bounds.length&&lastView.current!==viewKey){map.current.fitBounds(L.latLngBounds(bounds),{padding:[25,25],maxZoom:15});lastView.current=viewKey}});return()=>{cancelled=true}},[ready,points,paths,viewKey]);
 return <div className="public-map-wrap"><div ref={element} className="public-map" role="region" aria-label="Hartă interactivă a locurilor și traseului"/>{error&&<p role="status">{error}</p>}<p className="small-muted">Mișcă harta și folosește + / − pentru zoom. Atinge un punct pentru nume și detalii.</p></div>;
}
