'use client';
import {BookOpen, Smartphone, Share, Globe} from 'lucide-react';
import {useSyncExternalStore, useState} from 'react';
import {installPromptAvailable, promptInstall, subscribeInstallPrompt} from './install-prompt';
const GUIDES=[
 {revision:'35',file:'Aflivra_v35_Documentatie.pdf',summary:'fond și apel legate prin date și trimiteri oficiale'},
 {revision:'34',file:'Aflivra_v34_Documentatie.pdf',summary:'dosare urmărite la toate instanțele și ședințe păstrate integral'},
 {revision:'33',file:'Aflivra_v33_Documentatie.pdf',summary:'categorii și subcategorii după locația activă'},
 {revision:'32',file:'Aflivra_v32_Documentatie.pdf',summary:'cuprins apăsabil și copii consolidate confirmate'},
 {revision:'30',file:'Aflivra_v30_Documentatie.pdf',summary:'explorare, vreme și trailere'}];
export function BrowserInstall(){const available=useSyncExternalStore(subscribeInstallPrompt,installPromptAvailable,()=>false);const [installed,setInstalled]=useState(false);return <article className="source-download source-download-pwa"><span><Globe size={20}/><strong>Aplicația din browser · PWA</strong><small>Aplicația se instalează și direct din browser, unde browserul o oferă: în <strong>Chrome</strong> sau <strong>Edge</strong>, pe desktop sau Android, pictograma de instalare apare în bara de adrese sau în meniul browserului — sau chiar aici, din butonul de mai jos, când browserul tău îl oferă. Aplicația e același site, cu ecran complet și notificări, fără magazin și fără cont; actualizările vin odată cu site-ul.</small></span>{installed?<span className="text-link" role="status">Instalată — o găsești pe ecranul tău.</span>:available?<a className="text-link" href="#" onClick={e=>{e.preventDefault();void promptInstall().then(outcome=>{if(outcome==='accepted')setInstalled(true)})}}>Instalează aplicația acum</a>:<span className="text-link" aria-disabled="true">Instalarea din buton — doar când browserul o oferă</span>}</article>}

export function SourcePackages(){return <section className="live-section"><div className="panel-top"><div><span className="kicker">DOCUMENTAȚIA PLATFORMEI</span><h2>Ghidurile platformei</h2><p>Ghidul complet de folosire, publicat ca PDF odată cu fiecare revizie. Fiecare ediție documentează platforma așa cum a fost lansată la revizia ei și rămâne disponibilă aici.</p></div><BookOpen size={26}/></div>
<article className="source-download source-download-app"><span><Smartphone size={20}/><strong>Aplicația Android · Aflivra 1.0.0</strong><small>Învelișul instalabil al acestui site — același site, aceleași date, cu pictogramă proprie pe ecranul tău. Instalarea se face de aici, fără magazin de aplicații: Android îți cere o singură dată permisiunea de a instala din acest browser, în setările browserului, la primul sens. Pachetul e semnat de aflivra, iar verificarea legăturii cu site-ul se face prin declarația Digital Asset Links publicată la /.well-known/assetlinks.json.</small></span><a className="text-link" href="/downloads/aflivra.apk" download="aflivra.apk">Descarcă aplicația (.apk · 1,6 MB)</a></article>
<article className="source-download source-download-ios"><span><Share size={20}/><strong>Aplicația iOS · din Safari, fără App Store</strong><small>Pe iPhone instalarea fără App Store se face chiar din Safari, cu gestul propriului browser: deschide acest site în Safari → butonul <strong>Distribuie</strong> (pătratul cu săgeata în sus) → <strong>Adaugă la ecranul de start</strong>. Aplicația e același site — fără App Store și fără cont — cu pictograma și ecranul ei complet, pornind direct de pe ecranul de start; și notificările urmăritelor pornesc tot de aici, la fel ca în browser.</small></span></article>
<BrowserInstall/>
<div className="source-downloads">{GUIDES.map(g=><article className="source-download" key={g.file}><span>Ghidul platformei · revizia {g.revision}<small>{g.summary}</small></span><a className="text-link" href={'/downloads/'+g.file} download={g.file}>Descarcă PDF</a></article>)}</div></section>}
