'use client';
import {createSearchIndex,searchIndex,compareNames} from '@/lib/live/query';
import {SelectField} from './select-field';
import {SearchInput} from './search-input';
import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Download,Search,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';import {Button} from '@/components/ui/button';
import {snapshotJson} from './snapshot-store';import {Pagination} from './pagination';
import {normalizeSearch,paginate} from '@/lib/live/query';import {feedMedia} from '@/lib/live/media';
import {PublicMediaGallery} from './public-media';import {ExportActions} from './export-actions';
import {useSource} from './use-source';import {Freshness,dateText} from './live-data';
import illustrations from '@/public/media/category-illustrations.json';
type Story={id:string;title:string;categories:string[];authors?:string[];characters?:number;url:string;search?:string;file?:string;proof?:{bytes:number;sha256:string};unavailable?:boolean};
function StoryReader({story,fetchedAt,onClose}:{story:Story|null;fetchedAt:string;onClose:()=>void}){
 const [copy,setCopy]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[retry,setRetry]=useState(0);
 const live=useSource(story&&!story.file?'/api/story?id='+story.id:null,{timeoutMs:14000});
 useEffect(()=>{setCopy(null);setError('');if(!story?.file)return;const c=new AbortController();setLoading(true);snapshotJson('/stories/'+story.file,story.proof,c.signal).then(setCopy).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[story?.id,retry]);
 const data=copy||live.data?.data;
 return <Dialog open={!!story} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="v2 reader-dialog story-dialog"><DialogHeader><DialogTitle>{story?.title}</DialogTitle><DialogDescription>Wikisource · {(story?.authors||[]).join(' · ')||'Literatură și tradiții'}</DialogDescription></DialogHeader><div className="reader-body">{(loading||live.busy)&&<p role="status">Se încarcă textul integral…</p>}{(error||live.error||live.data?.status==='unavailable')&&<div className="live-error"><p>{error||live.error||live.data?.error}</p><Button variant="outline" onClick={()=>{setRetry(n=>n+1);live.retry()}}><RefreshCw size={16}/>Reîncearcă</Button></div>}{data&&<><div className="reader-actions"><ExportActions input={{title:data.title,text:data.content,subtitle:"Wikisource · "+(story?.authors||[]).join(", ")+" · "+data.url}} formats={["pdf"]} label="Descarcă povestea completă"/><span>{data.content.length.toLocaleString('ro-RO')} caractere · text integral</span></div><PublicMediaGallery items={data.media||feedMedia(data.html||'',data.url)} title={data.title}/><div className="reading-text story-text">{data.content.split(/\n+/).filter(Boolean).map((p:string,i:number)=><p key={i}>{p}</p>)}</div><div className="reader-provenance"><p>Copie integrală preluată: {dateText(data.fetchedAt||fetchedAt)}. Revizia Wikisource: {data.revision}.</p><p>{data.license}</p><a href={data.url} target="_blank" rel="noreferrer">Pagina exactă a poveștii</a> · <a href={data.licenseUrl} target="_blank" rel="noreferrer">Licență și atribuire</a></div></>}{live.data&&<Freshness source={live.data} documentUrl={story?.url}/>}</div></DialogContent></Dialog>;
}
export function StoriesWorkspace({initialQuery=''}:{initialQuery?:string}){
 const [manifest,setManifest]=useState<any>(null),[items,setItems]=useState<Story[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[q,setQ]=useState(initialQuery),[category,setCategory]=useState(''),[author,setAuthor]=useState(''),[sort,setSort]=useState('title'),[page,setPage]=useState(0),[selected,setSelected]=useState<Story|null>(null);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');snapshotJson('/stories/manifest.json',undefined,c.signal).then(async m=>{const data=await snapshotJson('/stories/index.json',m.index,c.signal);if(data.items.length!==m.count)throw Error('Catalogul poveștilor nu a fost primit integral.');setManifest(m);setItems(data.items)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[revision]);
 const categories=useMemo(()=>[...new Set(items.flatMap(x=>x.categories||[]))].sort(compareNames),[items]),authors=useMemo(()=>[...new Set(items.flatMap(x=>x.authors||[]))].sort(compareNames),[items]);
 const index=useMemo(()=>createSearchIndex(items,x=>({title:x.title,authors:x.authors,text:x.search})),[items]);
 const filtered=useMemo(()=>searchIndex(index,q).filter(x=>(!category||x.categories.includes(category))&&(!author||x.authors?.includes(author))).sort((a,b)=>sort==='length'?(b.characters||0)-(a.characters||0):compareNames(a.title,b.title)),[index,q,category,author,sort]);
 const selection=paginate(filtered,page,12),art=illustrations.find(x=>x.id==='cultura')!;
 return <section className="live-section stories-workspace"><div className="panel-top"><div><span className="kicker">BIBLIOTECĂ DE LECTURĂ</span><h2>Povești, basme și legende</h2><p>Texte de citit integral aici, cu autorul, ediția din sursă și căutare în conținut.</p></div><BookOpen size={30}/></div><div className="live-search"><Search size={18}/><SearchInput value={q} onValueChange={value=>{setQ(value);setPage(0)}} aria-label="Caută povești în titlu, autor și text integral" placeholder="Titlu, autor sau cuvinte din poveste"/></div><div className="entity-filters"><label><span className="control-label">Subcategorie</span><SelectField value={category} onChange={e=>{setCategory(e.target.value);setPage(0)}}><option value="">Toate</option>{categories.map(c=><option key={c}>{c}</option>)}</SelectField></label><label><span className="control-label">Autor</span><SelectField value={author} onChange={e=>{setAuthor(e.target.value);setPage(0)}}><option value="">Toți autorii</option>{authors.map(c=><option key={c}>{c}</option>)}</SelectField></label><label><span className="control-label">Ordonare</span><SelectField value={sort} onChange={e=>{setSort(e.target.value);setPage(0)}}><option value="title">Titlu A–Z</option><option value="length">Texte lungi întâi</option></SelectField></label></div>{loading&&<p role="status">Se încarcă biblioteca…</p>}{error&&<div className="live-error"><p>{error}</p><Button onClick={()=>setRevision(n=>n+1)}>Reîncearcă</Button></div>}{manifest&&<p className="small-muted">{manifest.count.toLocaleString('ro-RO')} fișe în categoriile Wikisource conectate · {manifest.completeTexts.toLocaleString('ro-RO')} texte integrale verificate · preluare {dateText(manifest.fetchedAt)}</p>}<div className="news-grid">{selection.items.map(s=><article key={s.id} className="news-card story-card"><figure className="story-cover"><img src={'/media/'+art.file} alt="Ilustrație reprezentativă pentru lectură" loading="lazy"/><figcaption>Ilustrație AI</figcaption><BookOpen size={36}/></figure><span className="kicker">{s.categories.slice(0,2).join(' · ')}</span><h3>{s.title}</h3><p>{s.authors?.join(' · ')||'Autor neprecizat în metadatele categoriei'}</p><p>{s.characters?s.characters.toLocaleString('ro-RO')+' caractere · text integral':'Textul se verifică la deschidere'}</p><Button variant="outline" onClick={()=>setSelected(s)}><BookOpen size={17}/>Citește povestea</Button></article>)}</div>{!loading&&!error&&!selection.total&&<p>Nu sunt povești pentru filtrele alese.</p>}<Pagination page={selection.page} pages={selection.pages} total={selection.total} onPage={setPage}/><StoryReader story={selected} fetchedAt={manifest?.fetchedAt} onClose={()=>setSelected(null)}/></section>;
}
