"use client";
import {fetchWithServerRetry} from '@/lib/http-retry.mjs';
import React,{useId,useState,useEffect} from 'react';
import {AreaChart,Area,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,PieChart,Pie,Cell,Legend} from 'recharts';
import {ChartContainer} from '@/components/ui/chart';
import {Button} from '@/components/ui/button';
import {Plus,Minus,LocateFixed} from 'lucide-react';
import {format} from './v2-model';
const colors=['#345179','#ddaf68','#839eab','#ad829c'];
export function DataChart({data,keys=['value'],labels=['Valoare'],type='area',unit='',height=250}:{data:Record<string,any>[];keys?:string[];labels?:string[];type?:string;unit?:string;height?:number}){
 const id=useId().replace(/:/g,'');const config=Object.fromEntries(keys.map((k,i)=>[k,{label:labels[i],color:colors[i%4]}]));
 return <div className="data-chart"><ChartContainer config={config} className="chart-canvas" style={{height,width:'100%',aspectRatio:'auto'}} aria-label={'Grafic: '+labels.join(', ')+'. Unitate: '+unit}>
 {type==='pie'?<PieChart accessibilityLayer><Pie data={data} dataKey="value" nameKey="name" innerRadius={62} outerRadius={88} paddingAngle={4} stroke="none" isAnimationActive={false}>{data.map((_,i)=><Cell key={i} fill={colors[i%4]}/>)}</Pie><Tooltip formatter={(v:any)=>[format(Number(v))+'%', 'Pondere']}/><Legend iconType="circle" iconSize={8}/></PieChart>:type==='bar'?<BarChart data={data} accessibilityLayer margin={{top:12,right:8,left:-15,bottom:0}}><CartesianGrid vertical={false} stroke="#e7e9ec"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#676e79'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#676e79'}}/><Tooltip formatter={(v:any,n:any)=>[format(Number(v),3)+' '+unit,labels[keys.indexOf(String(n))]||n]} contentStyle={{borderRadius:12,border:'1px solid #dfe2e5'}}/>{keys.map((k,i)=><Bar key={k} dataKey={k} fill={colors[i%4]} radius={[5,5,0,0]} maxBarSize={38} isAnimationActive={false}/>)}</BarChart>:<AreaChart data={data} accessibilityLayer margin={{top:12,right:8,left:-10,bottom:0}}><defs>{keys.map((k,i)=><linearGradient key={k} id={id+k} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={colors[i%4]} stopOpacity={.23}/><stop offset="100%" stopColor={colors[i%4]} stopOpacity={.015}/></linearGradient>)}</defs><CartesianGrid vertical={false} stroke="#e7e9ec"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#676e79'}}/><YAxis domain={unit==='RON'?['auto','auto']:[0,'auto']} axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#676e79'}}/><Tooltip formatter={(v:any,n:any)=>[format(Number(v),4)+' '+unit,labels[keys.indexOf(String(n))]||n]} contentStyle={{borderRadius:12,border:'1px solid #dfe2e5'}}/>{keys.map((k,i)=><Area key={k} type="monotone" dataKey={k} stroke={colors[i%4]} strokeWidth={2.5} fill={'url(#'+id+k+')'} isAnimationActive={false} connectNulls={false}/>)}</AreaChart>}
 </ChartContainer><details className="chart-table"><summary>Vezi valorile din grafic</summary><div className="table-scroll"><table><thead><tr><th>Etichetă</th>{keys.map((k,i)=><th key={k}>{labels[i]} ({unit||'%'})</th>)}</tr></thead><tbody>{data.map((r,i)=><tr key={i}><td>{r.name}</td>{keys.map(k=><td key={k}>{r[k]==null?'Indisponibil':format(Number(r[k]),4)}</td>)}</tr>)}</tbody></table></div></details></div>
}
export type Pin={id:string;name:string;lat:number;lon:number;label?:string};
function pinLabelLines(label:string){const lines:string[]=[];for(const word of label.split(/\s+/)){if(!lines.length||lines.at(-1)!.length+word.length>30)lines.push(word);else lines[lines.length-1]+=' '+word}return lines}
export function RomaniaMap({pins,selected,onSelect,compact=false}:{pins:Pin[];selected?:string;onSelect?:(id:string)=>void;compact?:boolean}){
 const [geo,setGeo]=useState<any>(null),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});
 useEffect(()=>{fetchWithServerRetry('/data/v2/map.json').then(r=>r.json()).then(setGeo).catch(()=>setGeo(false))},[]);
 const project=(lon:number,lat:number)=>[(lon-20)*61, (49.1-lat)*84];
 const path=(geometry:any)=>{const polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.coordinates;return polygons.map((poly:any)=>poly.map((ring:any)=>ring.map(([lon,lat]:number[],i:number)=>{const [x,y]=project(lon,lat);return (i?'L':'M')+x.toFixed(1)+','+y.toFixed(1)}).join(' ')+'Z').join(' ')).join(' ')};
 return <div className={'romap '+(compact?'compact':'')}><div className="map-grid"/><svg viewBox="0 0 640 490" role="group" aria-label="Harta României cu repere selectabile" onPointerDown={e=>{if((e.target as Element).tagName==='svg'){e.currentTarget.setPointerCapture(e.pointerId);(e.currentTarget as any)._last={x:e.clientX,y:e.clientY}}}} onPointerMove={e=>{const s=e.currentTarget as any;if(s.hasPointerCapture(e.pointerId)&&s._last){setPan(p=>({x:p.x+(e.clientX-s._last.x)*640/s.clientWidth,y:p.y+(e.clientY-s._last.y)*490/s.clientHeight}));s._last={x:e.clientX,y:e.clientY}}}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);(e.currentTarget as any)._last=null}}><g transform={`translate(${320*(1-zoom)+pan.x} ${245*(1-zoom)+pan.y}) scale(${zoom})`}>
 {geo?.features?.map((f:any)=><path key={f.properties.ADMIN} d={path(f.geometry)} fill={f.properties.ADM0_A3==='ROU'?'#d9dfe7':'#e6eaf0'} stroke="#f6f8fb" strokeWidth={2} pointerEvents="none"/>)}
 <text x="270" y="68" className="map-country">UCRAINA</text><text x="53" y="150" className="map-country">UNGARIA</text><text x="310" y="455" className="map-country">BULGARIA</text><text x="574" y="338" className="map-country sea">MAREA</text><text x="574" y="354" className="map-country sea">NEAGRĂ</text>
 {pins.map(p=>{const [x,y]=project(p.lon,p.lat),labelX=x>320?-17:16;return <g key={p.id} role="button" tabIndex={0} aria-label={'Selectează '+p.name} onClick={()=>onSelect?.(p.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect?.(p.id)}}} className={'map-pin '+(selected===p.id?'chosen':'')} transform={`translate(${x},${y})`}><title>{p.name}</title><circle r={selected===p.id?15:11} fill={selected===p.id?'#d9ad68':'#233b5d'} stroke="white" strokeWidth={3}/><circle r="3" fill="white"/>{(pins.length<=8||selected===p.id)&&<text x={labelX} y={4} textAnchor={x>320?'end':'start'} paintOrder="stroke" stroke="#edf1f7" strokeWidth={3} fill="#2b394d">{pinLabelLines(p.label||p.name).map((line,i)=><tspan x={labelX} dy={i?16:0} key={i}>{line}</tspan>)}</text>}</g>})}</g></svg>
 {geo===false&&<span className="map-fail">Fond de carte indisponibil. Reperele rămân selectabile.</span>}
 <div className="map-controls"><Button variant="outline" size="icon" aria-label="Mărește harta" onClick={()=>setZoom(z=>Math.min(2.8,z+.3))}><Plus size={17}/></Button><Button variant="outline" size="icon" aria-label="Micșorează harta" onClick={()=>setZoom(z=>Math.max(1,z-.3))}><Minus size={17}/></Button><Button variant="outline" size="icon" aria-label="Resetează harta" onClick={()=>{setZoom(1);setPan({x:0,y:0})}}><LocateFixed size={17}/></Button></div>
 <a className="map-credit" href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth · domeniu public · repere orientative</a></div>
}
