import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readSnapshotFile as readFile} from './snapshot-read.mjs';
import {writeFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';
import ts from 'typescript';
const root=resolve(import.meta.dirname,'..'),require=createRequire(import.meta.url),dir=await mkdtemp(join(tmpdir(),'aflivra-check-'));
try{
 for(const [name,file] of [['court-history','lib/court-history.ts'],['court-query','lib/court-query.ts'],['location-context','lib/location-context.ts'],['geographic-scope','lib/geographic-scope.ts'],['tabular-geography','lib/tabular-geography.ts']]){let source=await readFile(join(root,file),'utf8');for(const [binding,path] of [['countyLookup','public/data/locality-counties.json'],['urbanLocalities','public/data/geographic-localities.json']])source=source.replace('import '+binding+" from '@/"+path+"';",'const '+binding+'='+await readFile(join(root,path),'utf8')+';');source=source.replace("from './live/query'","from './query'").replace("import institutions from '@/public/courts/institutions.json';",'const institutions='+await readFile(join(root,'public/courts/institutions.json'),'utf8')+';');let js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,(_,p)=>"from '"+p+".mjs'");await writeFile(join(dir,name+'.mjs'),js)}
 for(const name of ['court-references','legal-portal','legal-registry','legal-consolidation','legal-selection','catalog-metadata','legal-reader','contacts','resource-download','source-xml','records','query','text','media','catalog-categories','adapters','feeds','legal','resources','knowledge','content','forecast','weather-gate','weather','transport','directories']){let source=await readFile(join(root,'lib/live',name+'.ts'),'utf8');source=source.replace("from '../court-history'","from './court-history'").replace("import confirmed from '@/public/courts/confirmed-references.json';",'const confirmed='+await readFile(join(root,'public/courts/confirmed-references.json'),'utf8')+';').replace("from '../court-query'","from './court-query'").replace("from '../geographic-scope'","from './geographic-scope'").replace("from '../tabular-geography'","from './tabular-geography'");source=source.replace("import audit from '@/public/catalog/audit.json';",'const audit='+await readFile(join(root,'public/catalog/audit.json'),'utf8')+';');source=source.replace("import codes from '@/public/legal-snapshots/manifest.json';",'const codes='+await readFile(join(root,'public/legal-snapshots/manifest.json'),'utf8')+';');source=source.replace("import courtInstitutions from '@/public/courts/institutions.json';",'const courtInstitutions='+await readFile(join(root,'public/courts/institutions.json'),'utf8')+';').replace("import {env} from 'cloudflare:workers';","const env={};");let output=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replaceAll('@/lib/http-retry.mjs',pathToFileURL(join(root,'lib/http-retry.mjs')).href);output=output.replace(/from '(\.\/[^']+)'/g,(_,p)=>"from '"+p+".mjs'");for(const pkg of ['xlsx','fflate'])output=output.replace("from '"+pkg+"'","from '"+pathToFileURL(require.resolve(pkg)).href+"'");await writeFile(join(dir,name+'.mjs'),output)}
 const adapters=await import(pathToFileURL(join(dir,'adapters.mjs'))),legal=await import(pathToFileURL(join(dir,'legal.mjs'))),feeds=await import(pathToFileURL(join(dir,'feeds.mjs'))),resources=await import(pathToFileURL(join(dir,'resources.mjs')));
 const selected=await import(pathToFileURL(join(dir,'legal-selection.mjs')));const reader=await import(pathToFileURL(join(dir,'legal-reader.mjs'))),contacts=await import(pathToFileURL(join(dir,'contacts.mjs')));
 const articleFixture='Fișa actului\nArticolul 1\n(1) Valoare 1 + 2 și … citarea Articolul 99 în alineat.\n\n(2) Text integral.\n\t+\nArticolul 2\nAl doilea articol.';
 const articleSections=reader.lawSections(articleFixture);assert.equal(articleSections.filter(x=>x.kind==='article').length,2);assert(reader.openLawArticle(articleSections,'article-0').body.includes('(2) Text integral.'));assert(reader.openLawArticle(articleSections,'article-0').body.includes('1 + 2 și …'));assert.equal(reader.openLawArticle(articleSections,'intro'),null);assert.equal(reader.openLawArticle(articleSections,'missing'),null);
 const oldPortalCopy='Articolul 1\n(1) Primul alineat.     ...       (2) Ultimul alineat.\n\nArticolul 2\nCitarea literală: A ... B.';const oldSections=reader.lawSections(oldPortalCopy);assert.equal(oldSections[0].body,'(1) Primul alineat.\n\n(2) Ultimul alineat.');assert(oldSections[1].body.includes('A ... B.'),'Literal omissions in quoted source text must remain intact');
 const snapshots=JSON.parse(await readFile(join(root,'public/legal-snapshots/manifest.json'),'utf8'));for(const code of snapshots.items){const original=await readFile(join(root,'public',code.file),'utf8'),clean=reader.readableLawText(original),sections=reader.lawSections(original);assert(sections.length>200);assert.equal(sections.map(s=>s.text).join(' ').replace(/\s+/g,' '),clean.replace(/\s+/g,' '),'Every source section must survive article splitting');assert(!/^[\t \u00a0]*\+[\t \u00a0]*$/m.test(clean));if(code.type==='CODUL CIVIL'){const first=reader.openLawArticle(sections,'article-0');for(let i=1;i<=6;i++)assert(first.body.includes('('+i+')'),'Civil Code article 1 must contain all six clauses');assert.equal(reader.lawDialogTitle(code),'Codul civil');const section57=sections.find(s=>s.title==='Articolul 57');assert(section57);assert(!section57.body.includes('Capitolul II'));assert(!section57.body.includes('Secţiunea 1'));const section58=sections.find(s=>s.title==='Articolul 58');assert(section58.body.includes('(1)')&&section58.body.includes('(2)'));assert(sections.some(s=>s.kind==='heading'&&s.title==='Secţiunea 1'));assert.equal(selected.findCodeCopy(snapshots.items,{id:'law-'+('f'.repeat(64)),exactTitle:code.title,selectedType:code.type,selectedNumber:code.number,selectedDate:code.date}),code)}}
 assert.equal(selected.resolveLawSelection([{id:'one',title:'Act identic'},{id:'two',title:'Act identic'}],{title:'Act identic'}),null);assert.equal(selected.resolveLawSelection([{id:'one',title:'Titlu complet',number:'1'},{id:'two',title:'Titlu complet',number:'2'}],{title:'Titlu complet',number:'2'}).id,'two');assert.equal(reader.lawSections('Secțiunea UNICĂ\nText integral.')[0].title,'Secțiunea UNICĂ');
 const contactFields=contacts.publicContacts({denumire:'Școală',telefon:'021 123 45 67; +40 712 345 678',Email:'secretariat@example.test',Website:'https://example.test',adresa:'Strada Exemplu nr. 1',CUI:'123456789',notes:'număr 0123456789',danger:{website:'javascript:alert(1)'}});assert.equal(contactFields.length,5);assert.equal(contactFields.filter(c=>c.kind==='phone').length,2);assert(!contactFields.some(c=>c.field==='CUI'||c.field==='notes'||c.href?.startsWith('javascript:')));assert.equal(contacts.publicContacts({websites:['https://example.test','https://example.test']}).length,1);
 console.log('Complete article reader verified against all six real code snapshots, including every clause of Civil Code article 1. Explicit contact extraction, safe destinations and deduplication passed.');
 const soap=x=>'<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body>'+x+'</s:Body></s:Envelope>';
 const act='<a:Legi><a:Titlu>LEGE nr. 1 din 2026 pentru test</a:Titlu><a:TipAct>LEGE</a:TipAct><a:Numar>1</a:Numar><a:DataVigoare>2026-01-01</a:DataVigoare><a:Emitent>Test automat</a:Emitent><a:Text>Articolul 1 &amp; detaliu. Articolul 2 '+('Text complet. '.repeat(2500))+'</a:Text></a:Legi>';
 const raw=soap('<SearchResult>'+act+act+'</SearchResult>');const rows=legal.parseLawSearch(raw).data.items;assert.equal(rows.length,1);assert.match(rows[0].id,/^law-[a-f0-9]{64}$/);assert.equal(rows[0].text,undefined);const full=legal.parseLawSearch(raw,true,rows[0].id).data.items[0];assert(full.text.length>24000);assert(full.text.includes('Articolul 2'));assert.equal(full.textProvided,true);assert.equal(legal.parseLawSearch(soap('<SearchResult/>')).data.items.length,0);assert.throws(()=>legal.parseLawSearch('<html>WAF</html>'));assert.throws(()=>legal.parseLawSearch(soap('<Fault/>')));assert.equal(legal.escapeXml('<&"'),'&lt;&amp;&quot;');
 const court=legal.parseCourtSearch(soap('<CautareDosareResult><Dosar><numar>1/2/2026</numar><institutie>Instanță de test</institutie><parti><DosarParte><nume>Parte test</nume><calitateParte>Reclamant</calitateParte></DosarParte></parti><sedinte><DosarSedinta><data>2026-01-02</data><solutieSumar>Text complet</solutieSumar></DosarSedinta></sedinte></Dosar></CautareDosareResult>')).data.items[0];assert.equal(court.parties[0].role,'Reclamant');assert.equal(court.hearings[0].summary,'Text complet');assert.equal(legal.parseCourtSearch(soap('<CautareDosareResponse/>')).data.items.length,0);assert.throws(()=>legal.parseCourtSearch(soap('<CautareDosareResponse><Unknown/></CautareDosareResponse>')));
 const proceeding=(stage,day,summary)=>'<Dosar><parti/><sedinte><DosarSedinta><data>'+day+'</data><solutieSumar><![CDATA['+summary+']]></solutieSumar><dataPronuntare i:nil="true"/></DosarSedinta></sedinte><numar>1/2/2026</numar><institutie>Instanță de test</institutie><data>2025-12-01</data><stadiuProcesual>'+stage+'</stadiuProcesual><dataModificare>2026-02-01</dataModificare></Dosar>';
 const foundation=proceeding('Fond','2026-01-02','Text integral. Valoarea 1 < 2.'),appeal=proceeding('Apel','2026-01-03','Apel'),otherHearing=proceeding('Fond','2026-01-04','Altă ședință');
 const multiple=legal.parseCourtSearch(soap('<CautareDosareResponse><CautareDosareResult>'+foundation+appeal+otherHearing+foundation+'</CautareDosareResult></CautareDosareResponse>')).data;
 assert.equal(multiple.items.length,3,'Same number and court must preserve different proceedings and different hearing collections');assert.equal(multiple.returnedRecords,4);assert.equal(multiple.hearingCount,3);assert.equal(new Set(multiple.items.map(x=>x.id)).size,3);assert(multiple.items.every(x=>x.date==='2025-12-01'));assert(multiple.items.every(x=>x.hearings[0].pronouncementDate===''));assert(multiple.items[0].hearings[0].summary.includes('1 < 2'));assert.equal(multiple.historyComplete,false);
 const prefixed=soap('<p:CautareDosareResponse xmlns:p="portalquery.just.ro"><p:CautareDosareResult>'+foundation.replace(/<(\/?)([A-Za-z])/g,'<$1p:$2')+'</p:CautareDosareResult></p:CautareDosareResponse>');assert.equal(legal.parseCourtSearch(prefixed).data.items[0].date,'2025-12-01');assert.throws(()=>legal.parseCourtSearch(soap('<CautareDosareResult>'+foundation.replace('</sedinte>','')+'</CautareDosareResult>')));assert.equal(legal.parseCourtSearch(soap('<CautareDosareResponse><CautareDosareResult i:nil="true"/></CautareDosareResponse>')).data.items.length,0);
 const limited=legal.parseCourtSearch(soap('<CautareDosareResult>'+foundation.repeat(1000)+'</CautareDosareResult>')).data;assert.equal(limited.items.length,1);assert.equal(limited.returnedRecords,1000);assert.equal(limited.limitReached,true,'Upstream truncation must use the raw count before deduplication');assert(legal.courtLoader('1/2/2026').key.startsWith('court:records.v5:'));assert.equal(legal.courtLoader('1/2/2026').version,'portal.deep-records.v6');
 const originalCourtFetch=globalThis.fetch,courtQuery={number:'1/2/2026',name:'',subject:'',institution:'',from:'',to:''};
 try{
  let calls=[],active=0,maxActive=0;
  const responseFor=(operation,records)=>soap('<'+operation+'Response><'+operation+'Result>'+records+'</'+operation+'Result></'+operation+'Response>');
  globalThis.fetch=async(url,init)=>{active++;maxActive=Math.max(maxActive,active);const operation=init.headers.SOAPAction.includes('CautareDosare2')?'CautareDosare2':'CautareDosare';calls.push(operation);assert(init.body.includes('<dataStart i:nil="true"/>'));if(operation==='CautareDosare2')assert(init.body.includes('<dataUltimaModificareStart i:nil="true"/>'));await new Promise(resolve=>setImmediate(resolve));active--;return new Response(responseFor(operation,operation==='CautareDosare'?foundation:foundation+appeal))};
  const combined=await legal.loadCourtSearch(courtQuery);assert.deepEqual(calls,['CautareDosare','CautareDosare2']);assert.equal(maxActive,1);assert.equal(combined.data.items.length,2);assert.equal(combined.data.hearingCount,2);assert.equal(combined.data.deepSearch.completed,true);assert.equal(combined.data.historyComplete,false);
  calls=[];globalThis.fetch=async(url,init)=>{const operation=init.headers.SOAPAction.includes('CautareDosare2')?'CautareDosare2':'CautareDosare';calls.push(operation);return new Response(responseFor(operation,calls.length===3?foundation:''))};const recovered=await legal.loadCourtSearch(courtQuery);assert.equal(calls.length,3);assert.equal(recovered.data.hearingCount,1);
  calls=[];globalThis.fetch=async(url,init)=>{const operation=init.headers.SOAPAction.includes('CautareDosare2')?'CautareDosare2':'CautareDosare';calls.push(operation);return new Response(responseFor(operation,''))};const empty=await legal.loadCourtSearch(courtQuery);assert.equal(calls.length,3);assert.equal(empty.data.items.length,0);assert.equal(empty.data.deepSearch.completed,true);
  calls=[];globalThis.fetch=async(url,init)=>{const operation=init.headers.SOAPAction.includes('CautareDosare2')?'CautareDosare2':'CautareDosare';calls.push(operation);return new Response(calls.length===1?'<html>Invalid 200 response</html>':responseFor(operation,foundation))};const repaired=await legal.loadCourtSearch(courtQuery);assert.equal(calls.length,3);assert.equal(repaired.data.items.length,1);assert.equal(repaired.warning,undefined,'Recovered checks must not remain marked unavailable');
  calls=[];globalThis.fetch=async(url,init)=>{calls.push(init.headers.SOAPAction);return calls.length===1?new Response(responseFor('CautareDosare',foundation)):new Response(null,{status:429,headers:{'Retry-After':'120'}})};const paused=await legal.loadCourtSearch(courtQuery);assert.equal(calls.length,2);assert.equal(paused.data.items.length,1);assert.equal(paused.data.deepSearch.completed,false);assert(paused.warning);assert.equal(paused.retryAfterSeconds,120);
  calls=[];globalThis.fetch=async(url,init)=>{calls.push(init.headers.SOAPAction);return new Response(null,{status:503})};await assert.rejects(()=>legal.loadCourtSearch(courtQuery),error=>error.diagnostic?.httpStatus===503&&error.diagnostic?.attempts===3);assert.equal(calls.length,3,'Exhausted HTTP retries must not be multiplied by the deep-search loop');
  console.log('Deep court retrieval verified: sequential official operations, lossless union, empty/invalid response recovery in three checks, 429 pause with retained data and at most three 5xx attempts.');
 }finally{globalThis.fetch=originalCourtFetch}
 const courtResponseArg=process.argv.indexOf('--court-response');if(courtResponseArg>=0){const path=process.argv[courtResponseArg+1],actual=legal.parseCourtSearch(await readFile(path,'utf8')).data;const expected=JSON.parse(execFileSync('python3',['-c',`import sys,json,xml.etree.ElementTree as E
r=E.parse(sys.argv[1]).getroot();ns={'p':'portalquery.just.ro'}
print(json.dumps([{'number':d.findtext('p:numar',namespaces=ns),'court':d.findtext('p:institutie',namespaces=ns),'date':d.findtext('p:data',namespaces=ns),'dates':[h.findtext('p:data',namespaces=ns) for h in d.findall('p:sedinte/p:DosarSedinta',ns)]} for d in r.findall('.//p:Dosar',ns)]))`,path],{encoding:'utf8'}));assert.deepEqual(actual.items.map(d=>({number:d.number,court:d.court,date:d.date,dates:d.hearings.map(h=>h.date)})),expected);assert.equal(actual.hearingCount,expected.reduce((total,d)=>total+d.dates.length,0));console.log('Real official court response independently compared with ElementTree: every returned record, registration date and hearing survived parsing.');}
 console.log('Court regressions passed: distinct proceedings and hearing collections, exact duplicates only, direct-child dates, nil fields, namespaces, malformed XML and the raw 1,000-record boundary.');
 const registry=adapters.parseRegistry(JSON.stringify({found:[{date_generale:{cui:427282,denumire:'Firma test',telefon:'0123456789',forma_juridica:'RA'},inregistrare_scop_Tva:{scpTVA:false},stare_inactiv:{statusInactivi:false}}]}),'427282','2026-10-04');assert.equal(registry.phone,'0123456789');assert.equal(registry.vat,false);assert.equal(adapters.parseRegistry('{"found":[]}','427282','2026-10-04'),null);
 // N05 — publishedAt un singur moment UTC: serviciul WordPress (date_gmt) e adevărul
 // sursei; meta description:published_time a paginii aplică aceeași oră GMT cu
 // fusul local lipit (probă TPBI 2026-10-08 15:08Z real vs 15:08+03:00 în meta).
 // Loader-ul citește wp-json ÎNTÂI, pagina HTML rămâne rezerva.
 {
  const content=await import(pathToFileURL(join(dir,'content.mjs')));
  const wpBody='[{"id":1,"link":"https://tpbi.ro/anunt-de-verificare/","title":{"rendered":"Anunț de verificare"},"content":{"rendered":"<p>Text integral de verificare.</p>","protected":false},"date_gmt":"2026-10-08T15:08:21"}]';
  const wpLoaded=content.parseWordPress(wpBody,'https://tpbi.ro/anunt-de-verificare/');
  assert.equal(wpLoaded.publishedAt,'2026-10-08T15:08:21Z','date_gmt+Z e momentul UTC publicat de sursă');
  const htmlPage='<html><head><meta property="article:published_time" content="2026-10-08T15:08:21+03:00"></head><body><div class="entry-content"><p>Text integral de verificare.</p></div></body></html>';
  const metaLoaded=content.parseArticlePage(htmlPage,'https://tpbi.ro/anunt-de-verificare/');
  assert.equal(metaLoaded.publishedAt,'2026-10-08T12:08:21.000Z','meta cu fus lipit produce momentul GREȘIT — de aceea wp-json se citește întâi');
  const loaderSource=await readFile(join(root,'lib/live/content.ts'),'utf8');
  assert.ok(loaderSource.indexOf('/wp-json/wp/v2/posts')<loaderSource.indexOf('parseArticlePage(await getSource'),'loader-ul citește serviciul WordPress înaintea paginii HTML');
  assert.match(loaderSource,/official\.article-body\.v4/,'versiunea v4 invalidează cache-ul cu publishedAt din meta');
 }
 const rss='<rss><channel>'+[1,2].map(n=>'<item><title>Un titlu complet</title><link>https://example.test/article'+(n===2?'?utm_source=test':'')+'</link><pubDate>Sun, 04 Oct 2026 08:00:00 GMT</pubDate><content:encoded><![CDATA[<p>'+('Conținut. '.repeat(3500))+'</p>]]></content:encoded></item>').join('')+'</channel></rss>';const articles=feeds.parseFeed(rss).data.items;assert.equal(articles.length,1);assert(articles[0].content.length>24000);assert.equal(articles[0].textComplete,true);
 const cell='x'.repeat(1200);assert.equal(resources.parseResource(new TextEncoder().encode(JSON.stringify([{a:cell,b:0}])),'JSON').data.sheets[0].rows[0][0],cell);
 const courtXml=legal.soapEnvelope(legal.courtRequest('2710/62/2022')),courtXml2=legal.soapEnvelope(legal.courtRequest('2710/62/2022','CautareDosare2')),lawXml=legal.soapEnvelope(legal.lawRequest({title:'Codul muncii',text:'',number:'',year:'',page:1},'contract-test'));
 execFileSync('python3',['-c',`import sys,json,xml.etree.ElementTree as E
from pathlib import Path
p=json.load(sys.stdin)
ns={'x':'http://www.w3.org/2001/XMLSchema'}
for family,operation in [('portalquery','CautareDosare'),('portalquery2','CautareDosare2'),('legislation','Search')]:
 schema=E.parse(Path(p['root'])/'scripts/contracts'/f'{family.removesuffix("2")}.wsdl.xml')
 declaration=next(x for x in schema.findall('.//x:element',ns) if x.attrib.get('name')==operation)
 expected=declaration.find('x:complexType/x:sequence',ns)
 request=E.fromstring(p[family]); body=request.find('{http://schemas.xmlsoap.org/soap/envelope/}Body'); actual=list(body)[0]
 assert actual.tag.split('}')[-1]==operation
 names=[x.tag.split('}')[-1] for x in actual]
 for field in expected:
  if field.attrib.get('minOccurs','1')!='0': assert field.attrib['name'] in names,field.attrib['name']
 declared=[x.attrib['name'] for x in expected]
 assert names==[x for x in declared if x in names]
 if family.startswith('portalquery'):
  for name in ('institutie','dataStart','dataStop'):
   field=next(x for x in actual if x.tag.split('}')[-1]==name)
   assert field.attrib.get('{http://www.w3.org/2001/XMLSchema-instance}nil')=='true'
 else:
  assert request.find('{http://schemas.xmlsoap.org/soap/envelope/}Header') is None
  model=actual.find('{http://tempuri.org/}SearchModel')
  assert model.find('{http://schemas.datacontract.org/2004/07/FreeWebService}RezultatePagina').text=='10'
`],{input:JSON.stringify({root,portalquery:courtXml,portalquery2:courtXml2,legislation:lawXml}),stdio:['pipe','pipe','pipe']});
 const responseArg=process.argv.indexOf('--legal-responses');if(responseArg>=0){const path=process.argv[responseArg+1];const lawLive=legal.parseLawSearch(await readFile(join(path,'law-live-response.xml'),'utf8'),true),courtLive=legal.parseCourtSearch(await readFile(join(path,'court-live-response.xml'),'utf8'));const labor=lawLive.data.items.find(x=>x.type==='LEGE'&&x.number==='53'&&x.title.includes('MUNCII'));assert(labor?.text?.length>160000);assert(labor.text.includes('Articolul 298'));assert(courtLive.data.items.length>0);assert(courtLive.data.items.every(x=>x.number==='2710/62/2022'&&x.court&&x.hearings.length));console.log('Real upstream responses verified: full labour-code text, stable official act links and court case details. No party names are printed.');}
 const text=await import(pathToFileURL(join(dir,'text.mjs'))),query=await import(pathToFileURL(join(dir,'query.mjs'))),media=await import(pathToFileURL(join(dir,'media.mjs'))),knowledge=await import(pathToFileURL(join(dir,'knowledge.mjs'))),content=await import(pathToFileURL(join(dir,'content.mjs'))),weather=await import(pathToFileURL(join(dir,'weather.mjs')));
 const encoded='<rss><channel><item><title>Encoded public article</title><link>https://www.edu.ro/test</link><pubDate>Sun, 04 Oct 2026 08:00:00 GMT</pubDate><description>&amp;lt;span&amp;gt;Un articol complet&amp;lt;/span&amp;gt;&amp;lt;div&amp;gt;&amp;lt;time datetime=&amp;quot;2026-10-04&amp;quot;&amp;gt;4 octombrie&amp;lt;/time&amp;gt;&amp;lt;/div&amp;gt;</description></item></channel></rss>';const cleanFeed=feeds.parseFeed(encoded).data.items[0];assert(!/<(?:span|div|time)/.test(cleanFeed.summary));assert(cleanFeed.summary.includes('Un articol complet'));assert(cleanFeed.summary.includes('4 octombrie'));assert.equal(text.sourceText('&lt;script&gt;alert(1)&lt;/script&gt;&lt;p&gt;Text sigur&lt;/p&gt;'),'Text sigur');assert.equal(text.sourceText('1 < 2 și 3 > 0'),'1 < 2 și 3 > 0');assert.equal(text.decodeEntities('&amp;lt;b&amp;gt;'),'<'+'b>');assert.equal(media.publicUrl('', 'https://example.test/article'),null);assert.equal(media.feedMedia('<video><source src="https://example.test/video.mp4"/></video><img src="https://example.test/a.jpg"/>','https://example.test/article').length,2);
 const gallery='<p>Text integral.</p><div data-config="{&quot;caption&quot;:&quot;&lt;span&gt;galerie&lt;/span&gt;&quot;}"><img src="https://example.test/image.jpg"/></div><p>Final.</p>';assert.equal(text.sourceText(gallery),'Text integral.\n\nFinal.');assert.equal(text.sourceText('Explicație data-config="{"x":1}" în text.'),'Explicație data-config="{"x":1}" în text.');const olderGallery='<p>Text integral.</p><div data-config="{"caption":"<span>galerie</span>","tabletHeight":800}"></div><p>Final.</p>';assert.equal(text.sourceText(olderGallery),'Text integral.\n\nFinal.');
 const allRows=Array.from({length:2101},(_,n)=>Object.fromEntries(Array.from({length:72},(_,c)=>['c'+c,c===71&&n===2100?'ultima valoare completă':n])));const parsed=resources.parseResource(new TextEncoder().encode(JSON.stringify(allRows)),'JSON').data.sheets[0];assert.equal(parsed.rows.length,2101);assert.equal(parsed.columns.length,72);assert.equal(parsed.rows[2100][71],'ultima valoare completă');assert.equal(parsed.rows[0][0],'0');const selection=resources.selectResourceRows(parsed.rows,{q:'ultima completă',page:0,sheet:0,sort:-1,desc:false});assert.equal(selection.total,1,'Search must include rows beyond the old preview boundary');assert.equal(resources.chunkRows(parsed.rows,30000).flat().length,2101);assert.equal(query.paginate([1,2,3],100,2).page,1);assert(query.matchesQuery({city:'Brașov',address:'Strada Muncii',zero:0},'brasov muncii 0'));
 const vat='RO427282';const linked=knowledge.parseKnowledge(JSON.stringify({results:{bindings:[{item:{value:'http://www.wikidata.org/entity/Q1'},itemLabel:{value:'Test'},vat:{value:vat},website:{value:'https://example.test/'}},{item:{value:'http://www.wikidata.org/entity/Q2'},vat:{value:'RO999999'}}]}}),'427282');assert.equal(linked.data.items.length,1);assert.equal(linked.data.items[0].vat,vat);assert.throws(()=>content.articleUrl('https://private.example.test/secret'));const article=content.parseArticle('<html><div class="entry-content"><p>Paragraf unu</p><div><p>Paragraf doi</p></div></div><footer>Nu face parte din articol</footer></html>','https://www.mai.gov.ro/test');assert(article.data.content.includes('Paragraf doi'));assert(!article.data.content.includes('Nu face parte'));assert.throws(()=>content.parseArticle('<html><div class="entry-content">Neterminat','https://www.mai.gov.ro/test'));
 if(responseArg>=0){const path=process.argv[responseArg+1];const education=feeds.parseFeed(await readFile(join(path,'education-live.xml'),'utf8'));assert(education.data.items.length>=10);assert(education.data.items.every(x=>!/<(?:span|div|time|p|a)\b/.test(x.summary)));const justice=JSON.parse(await readFile(join(path,'justice-actual-feed.json'),'utf8'));for(const item of justice.data.items)for(const key of ['title','summary','content']){const normalized=text.sourceText(item[key]);assert(!/<\/?(?:div|span|a|p|time)\b/i.test(normalized));assert(!normalized.includes('tabletHeight'))}console.log('Actual Justice gallery markup and older cached content verified without HTML or configuration leaks.');const forecast=weather.parseForecast(await readFile(join(path,'weather-live.json'),'utf8'));assert.equal(forecast.data.hourly.length,168);assert.equal(forecast.data.daily.length,7);assert.equal(Object.keys(forecast.data.current).length-2,15);assert.equal(weather.parseAlerts('<?xml version="1.0"?><avertizari/>').data.empty,true);console.log('Actual education RSS verified without visible HTML; actual full forecast verified: 15 current, 42 hourly and 21 daily variables.');}
 const prior=globalThis.fetch;let seen=[];globalThis.fetch=async(url,init)=>{seen.push({url:String(url),init});return seen.length===1?new Response(null,{status:301,headers:{location:'https://www.example.test/feed/'}}):new Response('ok')};assert.equal(await adapters.getSource('https://example.test/feed/'),'ok');assert.equal(seen.length,2);globalThis.fetch=async()=>new Response(null,{status:302,headers:{location:'http://example.test/feed/'}});await assert.rejects(()=>adapters.getSource('https://example.test/feed/'),/adresă/);globalThis.fetch=prior;
 console.log('Verified: official SOAP contracts, complete legal/RSS text, act identity, public case fields, ANAF contacts, missing values, full cells and safe redirects. Test fixtures are never imported by the app.');
}finally{await rm(dir,{recursive:true,force:true})}
