import {readSnapshotFile as readFile} from './snapshot-read.mjs';
import {join,resolve} from 'node:path';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'../public/catalog'),audit=JSON.parse(await readFile(join(root,'audit.json'),'utf8')),index=JSON.parse(await readFile(join(root,'index.json'),'utf8'));assert.equal(index.items.length,audit.datasets);assert.equal(new Set(index.items.map(d=>d.id)).size,audit.datasets);let references=0,ids=new Set();for(const d of index.items){const raw=await readFile(join(root,'datasets',d.id+'.json'));assert.equal(createHash('sha256').update(raw).digest('hex'),audit.datasetChecksums[d.id]);const file=JSON.parse(raw);assert.equal(file.id,d.id);assert.equal(file.resources.length,d.resourceCount);references+=file.resources.length;for(const r of file.resources)ids.add(r.id)}assert.equal(references,audit.resourceReferences);assert.equal(ids.size,audit.uniqueResourceIds);assert.equal(audit.fileContentsVerified,false);const manifest=JSON.parse(await readFile(resolve(root,'../media/category-manifest.json'),'utf8'));assert.equal(manifest.length,28);for(const image of manifest){assert(image.credit&&image.license&&image.licenseUrl&&image.sourceUrl);const bytes=await readFile(resolve(root,'../media',image.file));assert.equal(bytes.toString('ascii',0,4),'RIFF');assert.equal(bytes.toString('ascii',8,12),'WEBP')}console.log(`Catalog round-trip passed: ${audit.datasets} complete dataset metadata files, ${references} distinct resource references, ${audit.publishers} publishers, all SHA-256 hashes and 28 attributed photos. Resource file bodies are verified separately at import.`);

const laws=JSON.parse(await readFile(resolve(root,'../legal-snapshots/manifest.json'),'utf8'));assert.equal(laws.items.length,6);for(const law of laws.items){const bytes=await readFile(resolve(root,'..'+law.file));const text=bytes.toString('utf8');assert.equal(text.length,law.characters);assert.equal(bytes.length,law.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),law.sha256);assert(text.includes('Articolul'));assert(text.length>150000)}console.log('Six complete official code snapshots verified again: bytes, characters and SHA-256; fallback never uses invented text.');

const categories=new Set(manifest.map(m=>m.category));assert.equal(categories.size,14);for(const category of categories)assert.equal(manifest.filter(m=>m.category===category).length,2);const unclassified=index.items.filter(d=>!d.categories.length);assert(unclassified.length>0);assert.equal(index.items.filter(d=>d.categories.length).length+unclassified.length,audit.datasets);console.log(`Category coverage verified: 14 domains with two photographs each, plus ${unclassified.length} explicitly unclassified datasets reachable through Other Public Data and All Data.`);

const artwork=JSON.parse(await readFile(resolve(root,'../media/category-illustrations.json'),'utf8'));assert.equal(artwork.length,16);assert.equal(new Set(artwork.map(m=>m.id)).size,16);assert.equal(new Set(artwork.map(m=>m.sha256)).size,15);for(const item of artwork){const bytes=await readFile(resolve(root,'../media',item.file));assert.equal(bytes.length,item.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),item.sha256);assert.equal(bytes.toString('ascii',8,12),'WEBP');assert(item.caption.includes('AI'));assert(item.prompt&&item.provenance.generationCallsForAsset===1)}const hero=JSON.parse(await readFile(resolve(root,'../media/hero-style.json'),'utf8')),heroBytes=await readFile(resolve(root,'../media',hero.file));assert.equal(createHash('sha256').update(heroBytes).digest('hex'),hero.webpExport.sha256);assert(hero.credit&&hero.licenseUrl&&hero.changesRo);console.log('New editorial collection verified: 16 category covers (15 distinct assets) with prompts, sizes, SHA-256 and AI labels; stylized hero attribution and checksum.');

const copies=JSON.parse(await readFile(resolve(root,'../resource-copies/manifest.json'),'utf8'));assert.equal(copies.copies.length,2);for(const copy of copies.copies){const bytes=await readFile(resolve(root,'..'+copy.file));assert.equal(bytes.length,copy.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),copy.fileSha256);assert(Number.isFinite(Date.parse(copy.fetchedAt)))}console.log('Actual CSV/PDF initial copies verified: complete original file bytes, SHA-256 and real retrieval dates.');
